import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'hi' | 'mr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, fallback?: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Nav
    'nav.home': 'Home',
    'nav.programs': 'Programs',
    'nav.contact': 'Contact',
    'nav.signIn': 'Sign In',
    'nav.register': 'Register',
    'nav.enquireNow': 'Enquire Now',
    'nav.menu': 'Menu',
    'nav.logout': 'Logout',
    'nav.studentPortal': 'Student Portal',
    'nav.learningLab': 'Neural Memory Lab',
    'nav.streak': 'Streak',
    'nav.sparks': 'Sparks',
    'nav.days': 'Days',

// Drawer & Navigation
    'nav.navigation': 'Navigation',
    'nav.programsMasterclasses': 'Programs & Masterclasses',
    'nav.explore': 'Explore BrainSetu',
    'nav.about': 'About Us',
    'nav.aboutDesc': 'Our vision, philosophy and mission',
    'nav.approach': 'Learning Approach',
    'nav.approachDesc': 'The 6-step mastery methodology',
    'nav.tech': 'Technology',
    'nav.techDesc': 'Digital practice & Intellia360 tools',
    'nav.studentDev': 'Student Development',
    'nav.studentDevDesc': 'Cognitive skills & growth beyond marks',
    'nav.forParents': 'For Parents',
    'nav.forParentsDesc': 'Parent guidance and learning gap diagnosis',
    'nav.contactAdmissions': 'Contact & Admissions',
    'nav.contactDesc': 'Schedule a diagnostic consultation',
    'nav.studentPortalDesc': 'Sign in to access the Neural Memory Lab (Module 3) & save progress.',
    'nav.launchLab': 'Launch Neural Memory Lab',
    'nav.bookConsultation': 'Book Diagnostic Consultation',
    'nav.academyAddress': 'Feliz Flow Studio, Next to Hiranandani Trust School, Panvel – 410207',
    'nav.privacyPolicy': 'Privacy Policy',
    'nav.terms': 'Terms & Conditions',

    // About Page
    'about.breadcrumb': 'About Us',
    'about.heroTitle': 'About BrainSetu Academy',
    'about.heroDesc1': 'BrainSetu Academy is a modern learning and student-development initiative engineered to eliminate mechanical, anxiety-driven rote memorization from education.',
    'about.heroDesc2': 'The word "Setu" means bridge. BrainSetu embodies the intellectual and psychological bridge connecting:',
    'about.bridgeKnowledge': 'Knowledge',
    'about.bridgeMemory': 'Memory',
    'about.bridgeConcepts': 'Concepts',
    'about.bridgeApplication': 'Application',
    'about.bridgePotential': 'Potential',
    'about.philosophyTitle': 'Our Philosophy',
    'about.philosophyDesc': 'We combine first-principles mathematical reasoning, deliberate memory retention frameworks, and empathetic mentorship to nurture fearless, confident lifelong thinkers.',

    // Learning Approach Page
    'approach.breadcrumb': 'Learning Approach',
    'approach.heroTitle': 'The BrainSetu Learning Approach',
    'approach.heroSubtitle': 'Moving from mechanical memorization to enduring understanding through structured cognitive progressions and scientific memory encoding.',
    'approach.stepTitle': 'The Six-Step Mastery Progression',
    'approach.stepSubtitle': 'Every concept is taught through a purposeful sequence that builds intuitive clarity before moving to complex application.',

    // Technology Page
    'technology.breadcrumb': 'Technology & AI',
    'technology.heroTitle': 'Technology That Amplifies Human Understanding',
    'technology.heroSubtitle': 'We believe technology should never replace the empathy and diagnostic intuition of a master educator. Instead, it serves as an interactive cognitive prosthesis that makes abstract mathematics tangible, visual, and measurable.',
    'technology.exploreBtn': 'Explore Programs',
    'technology.enquireBtn': 'Book Diagnostic Assessment',

    // Student Development Page
    'studentDev.breadcrumb': 'Student Development',
    'studentDev.heroTitle': 'Developing the Whole Thinker',
    'studentDev.heroSubtitle': 'Cognitive skills, emotional composure, and meta-learning disciplines that endure far beyond tests and board exams.',
    'studentDev.outcomesTitle': 'Eight Foundational Cognitive Outcomes',
    'studentDev.outcomesSubtitle': 'Every student develops these vital cognitive muscles during their journey with BrainSetu.',

    // Parents Page
    'parents.breadcrumb': 'For Parents',
    'parents.heroTitle': 'Helping Parents Understand How Their Child Learns',
    'parents.heroSubtitle': 'Math anxiety is rarely a lack of intelligence; it is almost always an unaddressed prerequisite concept gap or mechanical teaching method. We empower parents with clarity, empathy, and actionable frameworks.',
    'parents.bookBtn': 'Book a Counselling / Assessment Enquiry',
    'parents.exploreBtn': 'Explore Recommended Tracks',

    // Contact Page
    'contact.breadcrumb': 'Contact & Admissions',
    'contact.heroTitle': 'Contact & Diagnostic Admissions',
    'contact.heroSubtitle': 'Speak with our senior academic mentors or visit our Panvel center for a 1-on-1 diagnostic consultation for your child.',
    'contact.addressTitle': 'Panvel Learning Center',
    'contact.hoursTitle': 'Operating Hours',
    'contact.hoursDesc': 'Mon - Sat: 10:00 AM – 7:30 PM',
    'contact.phoneTitle': 'Phone & WhatsApp',
    'contact.formTitle': 'Schedule Diagnostic Consultation',
    'contact.formSubtitle': 'Fill out the form below and our academic counsellor will reach out within 24 hours.',

    'about.visionBadge': 'Our Vision',
    'about.visionQuote': 'To build a generation of learners who don’t just memorize information, but understand, retain, apply, and confidently use their knowledge.',
    'about.philosophyBadge': 'Guiding Principle',
    'about.philosophyHeading': 'Our Philosophy',
    'about.philosophyQuote': '“Learning should create understanding, not just recall.”',
    'about.activePartTitle': 'Active Participation',
    'about.activePartDesc': 'Students should actively participate in their learning journey—questioning, experimenting, deriving, and defending conclusions rather than passively absorbing formulas.',
    'about.holisticDevTitle': 'Holistic Development',
    'about.holisticDevDesc': 'Academic performance and lifelong cognitive skills should develop together. High exam scores are natural outcomes of genuine intellectual mastery.',
    'about.missionBadge': 'Purpose In Action',
    'about.missionTitle': 'Our Eight-Fold Mission',
    'about.missionSubtitle': 'The specific, measurable commitments that steer our curriculum, mentorship, and technology.',
    'about.corePillar': 'Core Pillar',
    'about.mission1Title': 'Improve Memory & Retention',
    'about.mission1Desc': 'Replace fragile short-term cramming with durable semantic memory techniques.',
    'about.mission2Title': 'Develop Logical & Analytical Thinking',
    'about.mission2Desc': 'Instill structured deductive reasoning and algorithmic step-by-step clarity.',
    'about.mission3Title': 'Strengthen Academic Fundamentals',
    'about.mission3Desc': 'Eradicate prerequisite conceptual gaps so higher math becomes intuitive.',
    'about.mission4Title': 'Make Learning Engaging',
    'about.mission4Desc': 'Transform intimidating equations into interactive, visual discoveries and puzzles.',
    'about.mission5Title': 'Reduce Rote Memorization',
    'about.mission5Desc': 'Promote first-principles understanding: derive and visualize before memorizing.',
    'about.mission6Title': 'Build Academic Confidence',
    'about.mission6Desc': 'Foster poise and fearlessness when encountering non-routine, complex challenges.',
    'about.mission7Title': 'Personalized Academic Guidance',
    'about.mission7Desc': 'Acknowledge individual cognitive fingerprints with tailored mentor support.',
    'about.mission8Title': 'Modern Technology Integration',
    'about.mission8Desc': 'Harmonize passionate human mentorship with future-ready Intellia360 tools.',
    'whoWeServe.badge': 'Tailored Developmental Stages',
    'whoWeServe.title': 'Learning Designed for Every Stage',
    'whoWeServe.subtitle': 'From early play-based pattern recognition to advanced competitive Olympiad proofs, our curriculum adapts to each developmental milestone.',
    'whoWeServe.exploreBtn': 'Explore Stage Tracks',
    'whoWeServe.stage1Stage': 'Pre-Primary',
    'whoWeServe.stage1Age': 'Ages 4 – 6',
    'whoWeServe.stage1Headline': 'Curiosity & Foundational Thinking',
    'whoWeServe.stage1Desc': 'Nurture early number sense, spatial awareness, and intuitive pattern recognition through playful multi-sensory games.',
    'whoWeServe.stage1Badge': 'Early Explorers',
    'whoWeServe.stage2Stage': 'Primary',
    'whoWeServe.stage2Age': 'Grades 1 – 5',
    'whoWeServe.stage2Headline': 'Strong Mathematical Foundations',
    'whoWeServe.stage2Desc': 'Transform basic arithmetic into solid conceptual scaffolding, removing number anxiety before it can take root.',
    'whoWeServe.stage2Badge': 'Core Foundation',
    'whoWeServe.stage3Stage': 'Middle School',
    'whoWeServe.stage3Age': 'Grades 6 – 8',
    'whoWeServe.stage3Headline': 'Conceptual Understanding & Reasoning',
    'whoWeServe.stage3Desc': 'Bridge concrete numbers with algebraic abstraction, geometric reasoning, and cognitive memory techniques.',
    'whoWeServe.stage3Badge': 'Concept Builders',
    'whoWeServe.stage4Stage': 'Secondary',
    'whoWeServe.stage4Age': 'Grades 9 – 10',
    'whoWeServe.stage4Headline': 'Academic Mastery & Problem Solving',
    'whoWeServe.stage4Desc': 'Master rigorous board curricula, systematic exam execution, multistep proofs, and high-order thinking.',
    'whoWeServe.stage4Badge': 'Board Excellence',
    'whoWeServe.stage5Stage': 'Higher Secondary',
    'whoWeServe.stage5Age': 'Grades 11 – 12',
    'whoWeServe.stage5Headline': 'Advanced Mathematical & Competitive Foundations',
    'whoWeServe.stage5Desc': 'Equip aspirants with Olympiad proof methods, advanced calculus, and deep analytical problem synthesis.',
    'whoWeServe.stage5Badge': 'Competitive Edge',
    'parents.pillarsBadge': 'Parental Enablement',
    'parents.pillarsTitle': 'Five Pillars of Our Parent Guidance',
    'parents.pillarsSubtitle': 'Concrete ways we keep parents informed, supported, and confident in their child’s academic journey.',
    'parents.pillar1Title': 'Understand Learning Styles',
    'parents.pillar1Desc': 'Discover how your child processes spatial, verbal, and numerical concepts to support them without frustration.',
    'parents.pillar2Title': 'Identify Hidden Learning Gaps',
    'parents.pillar2Desc': 'Pinpoint subtle foundational misconceptions from prior academic years that cause present-day math anxiety.',
    'parents.pillar3Title': 'Track Holistic Cognitive Development',
    'parents.pillar3Desc': 'Follow concrete indicators of attention span, working memory retention, and autonomous problem-solving growth.',
    'parents.pillar4Title': 'Mentoring Consultations & Updates',
    'parents.pillar4Desc': 'Receive transparent, actionable feedback and direct access to dedicated mentors.',
    'parents.pillar5Title': 'Cultivate Better Habits at Home',
    'parents.pillar5Desc': 'Actionable parenting frameworks to turn homework time into an enjoyable, stress-free confidence ritual.',
    'parents.journeyBadge': 'Parent Journey',
    'parents.journeyTitle': 'The 7-Step Parent Partnership Journey',
    'parents.journeySubtitle': 'How we guide families from initial diagnostic enquiry to continuous long-term intellectual growth.',
    'approach.methodBadge': 'Progression Framework',
    'approach.methodTitle': 'The Six-Step Mastery Progression',
    'approach.methodSubtitle': 'Every concept is taught through a purposeful sequence that builds intuitive clarity before moving to complex application.',
    'approach.stepFocus': 'Focus:',
    'approach.stepBridge': 'Bridge:',
    'approach.techBadge': 'Cognitive Science In Action',
    'approach.techTitle': 'Six Cognitive Techniques',
    'approach.techSubtitle': 'Scientific retention tools integrated into every lesson to make memory effortless and reliable under exam pressure.',
    'approach.techHow': 'How it works:',
    'approach.techExample': 'Classroom example:',
    'approach.tech1Name': 'Concept Chunking',
    'approach.tech1Desc': 'Breaking complex formulas and concepts into cohesive mental packets.',
    'approach.tech1How': 'Our working memory can comfortably hold 4–7 chunks at once. By logically organizing lengthy proofs into 3 core steps, students process intricate math effortlessly.',
    'approach.tech1Example': 'Grouping polynomial factorization into: Common terms -> Pattern match (Difference of squares) -> Middle-term split.',
    'approach.tech2Name': 'Logical Connections',
    'approach.tech2Desc': 'Anchoring new topics to already mastered foundational principles.',
    'approach.tech2How': 'The brain remembers by association. When a student sees that Coordinate Geometry is simply Algebra meeting Euclidean Space, the brain readily integrates the new concept.',
    'approach.tech2Example': 'Linking the Pythagorean Theorem directly to the Distance Formula and Circle Equations.',
    'approach.tech3Name': 'Recall Practice (Active Retrieval)',
    'approach.tech3Desc': 'Strengthening neural pathways through deliberate self-testing.',
    'approach.tech3How': 'Reading a textbook creates an illusion of competence. Closing the book and attempting to reconstruct the derivation strengthens synaptic connections permanently.',
    'approach.tech3Example': 'Low-stakes 5-minute flash challenges where students write out the logic of a formula from scratch.',
    'approach.tech4Name': 'Visual Associations',
    'approach.tech4Desc': 'Transforming abstract symbols into vivid spatial and sensory representations.',
    'approach.tech4How': 'Visual cortex processing is extraordinarily fast and durable. We teach students to picture equations as geometric transformations and physical balancing scales.',
    'approach.tech4Example': 'Visualizing equations as a balanced beam scale where balancing operations must be symmetrically applied.',
    'approach.tech5Name': 'Pattern Recognition',
    'approach.tech5Desc': 'Spotting recurring structural symmetries across seemingly different problems.',
    'approach.tech5How': 'Mathematicians do not solve thousands of disconnected problems; they recognize underlying archetypes. We train students to detect underlying structural motifs.',
    'approach.tech5Example': 'Identifying telescoping sums, invariants in sequences, and symmetry in algebraic expressions.',
    'approach.tech6Name': 'Structured Spaced Revision',
    'approach.tech6Desc': 'Revisiting concepts at scientifically calibrated time intervals.',
    'approach.tech6How': 'Combatting the Ebbinghaus forgetting curve. Revisiting material on Day 1, Day 3, Day 7, and Day 21 resets the memory decay curve to near zero.',
    'approach.tech6Example': 'Curated 10-minute micro-reviews scheduled precisely when memory decay begins to set in.',
    'technology.pillarsBadge': 'Integrated Modalities',
    'technology.pillarsTitle': 'Three Pillars of the BrainSetu Experience',
    'technology.pillarsSubtitle': 'Each modality plays a distinct, non-redundant role in shaping the learner’s intellectual journey.',
    'technology.pillar1Title': 'Physical Learning',
    'technology.pillar1Tag': 'Human Mentor Interaction',
    'technology.pillar1Desc': 'Expert mentor-led instruction, interactive Socratic discussions, and personal attention to build confidence.',
    'technology.pillar2Title': 'Digital Learning',
    'technology.pillar2Tag': 'Interactive Software & Visuals',
    'technology.pillar2Desc': 'Dynamic mathematics visualizations, interactive geometry tools, and gamified practice to make concepts intuitive.',
    'technology.pillar3Title': 'AI-Powered Diagnostics',
    'technology.pillar3Tag': 'Intellia360 Learning Engine',
    'technology.pillar3Desc': 'Intelligent diagnostic assessments, personalized revision recommendations, and progress tracking.',
    'technology.featuresBadge': 'Digital Intelligence',
    'technology.featuresTitle': 'Powered by the Future-Ready Intellia360 Ecosystem',
    'technology.featuresSubtitle': 'The underlying software engine connecting student practice, diagnostic assessment, and analytical feedback loops.',
    'studentDev.pillarsBadge': 'Cognitive Taxonomy',
    'studentDev.pillarsTitle': 'The Nine Pillars of Student Development',
    'studentDev.pillarsSubtitle': 'Click each skill to explore its cognitive mechanism and the exact pedagogical drills used at BrainSetu Academy.',
    'studentDev.mechanismLabel': 'The Cognitive Mechanism:',
    'studentDev.drillLabel': 'BrainSetu Pedagogical Drill:',
    'studentDev.outcomeLabel': 'Measurable Student Outcome:',
    'studentDev.trackingTitle': 'Illustrative Diagnostic Analytics Dashboard',
    'studentDev.trackingSubtitle': 'Real-time multi-dimensional tracking of cognitive stamina and mathematical retention across practice sets.',
    'contact.formHeading': 'Schedule a Consultation',
    'contact.formSub': 'Fill out the form below and our academic counselling team will contact you within 24 hours.',
    'contact.nameLabel': 'Parent / Student Full Name',
    'contact.namePlaceholder': 'e.g. Ramesh Sharma',
    'contact.gradeLabel': 'Student Grade / Class',
    'contact.gradePlaceholder': 'e.g. Grade 7, CBSE / ICSE',
    'contact.phoneLabel': 'Mobile Number / WhatsApp',
    'contact.phonePlaceholder': '+91 98765 43210',
    'contact.emailLabel': 'Email Address',
    'contact.emailPlaceholder': 'parent@example.com',
    'contact.programLabel': 'Program of Interest',
    'contact.methodLabel': 'Preferred Contact Method',
    'contact.messageLabel': 'Message / Specific Learning Challenges (Optional)',
    'contact.messagePlaceholder': 'Describe any concepts your child finds difficult...',
    'contact.submitBtn': 'Submit Diagnostic Enquiry',
    'contact.submittingBtn': 'Submitting...',
    'contact.privacyNotice': 'We respect family privacy. Your contact details are strictly confidential.',

    // Hero
    'hero.badge': 'Premier Cognitive & Mathematics Academy',
    'hero.titleLine1': 'Building Smarter Minds.',
    'hero.titleLine2': 'Creating Confident Learners.',
    'hero.subtitle': 'Learn faster, remember better, think smarter, and perform with confidence. BrainSetu represents the bridge between Knowledge → Understanding → Application → Confidence.',
    'hero.exploreBtn': 'Explore Programs',
    'hero.enquireBtn': 'Enquire Now',
    'hero.statStudents': '10,000+ Students Guided',
    'hero.statRetention': '10X Memory Retention',
    'hero.statConfidence': '98% Math Confidence',

    // Impact Section
    'impact.badge': 'Our Measurable Impact',
    'impact.title': 'Proven Track Record of Excellence',
    'impact.subtitle': 'Empowering learners, educators, and schools across the nation with research-backed cognitive and conceptual learning methodologies.',
    'impact.stat1Label': 'Successful Registrations',
    'impact.stat2Label': 'Active Members',
    'impact.stat3Label': 'Years of Experience',
    'impact.stat4Label': 'Live Webinars',
    'impact.stat5Label': 'Seminars & Workshops',
    'impact.stat6Label': 'Schools We Work With',

    // Why BrainSetu Section
    'why.title': 'More Than Just Learning',
    'why.subtitle': 'BrainSetu combines mathematics, cognitive development, memory techniques, mentoring, and technology to create a more meaningful learning experience.',
    'why.benefit1Title': 'Conceptual Learning',
    'why.benefit1Desc': 'Understand the "why" behind mathematical relationships rather than passively memorizing rules.',
    'why.benefit2Title': 'Logical Thinking',
    'why.benefit2Desc': 'Develop structured deduction, pattern recognition, and analytical clarity that transfer to any domain.',
    'why.benefit3Title': 'Memory Techniques',
    'why.benefit3Desc': 'Scientific concept chunking and active recall methods that make retention effortless and stress-free.',
    'why.benefit4Title': 'Problem-Solving & Technology',
    'why.benefit4Desc': 'Independent problem-solving heuristics supported by modern digital mathematics learning tools.',

    // Video Showcase Section
    'video.badge': 'Official Video Showcase',
    'video.title': 'Experience BrainSetu in Action',
    'video.subtitle': 'Watch how our cognitive development methodology and the Intellia 360 Mathematics Program transform conceptual clarity, analytical thinking, and lifelong confidence.',
    'video.feat1Title': 'Conceptual Clarity',
    'video.feat1Desc': 'First-principles mathematical reasoning that banishes rote memorization.',
    'video.feat2Title': '10X Memory Power',
    'video.feat2Desc': 'Scientific concept chunking and neural recall techniques.',
    'video.feat3Title': 'Expert Mentorship',
    'video.feat3Desc': 'Dedicated mentors paired with adaptive digital practice tools.',
    'video.watchYoutube': 'Watch Directly on YouTube',

    // Learning Journey Section
    'journey.title': 'The Learning Journey',
    'journey.subtitle': 'A clear six-step cognitive progression that transforms new concepts into lifelong understanding and mastery.',
    'journey.stage': 'Stage',
    'journey.step1Title': 'Learn',
    'journey.step1Desc': 'Introduce the concept with intuition and real-world curiosity.',
    'journey.step2Title': 'Understand',
    'journey.step2Desc': 'Build conceptual clarity from first principles.',
    'journey.step3Title': 'Remember',
    'journey.step3Desc': 'Use memory techniques and meaningful neural connections.',
    'journey.step4Title': 'Practice',
    'journey.step4Desc': 'Reinforce through deliberate, tiered exercise sets.',
    'journey.step5Title': 'Apply',
    'journey.step5Desc': 'Use knowledge in non-routine problems and real situations.',
    'journey.step6Title': 'Master',
    'journey.step6Desc': 'Track progress, close feedback loops, and achieve enduring mastery.',

    // Programs Section
    'programs.sectionBadge': 'Cognitive & Math Pathways',
    'programs.sectionTitle': 'Programs Designed for Smarter Learning',
    'programs.sectionSubtitle': 'Choose from our specialized memory masterclass and our premier conceptual mathematics curriculum.',
    'programs.enquireBtn': 'Enquire & Book Diagnostic',
    'programs.original': 'Original:',
    'programs.webinarTitle': '10X Memory Power Webinar',
    'programs.webinarShortDesc': 'Complete step-by-step course to boost your memory power by 10X. Learn advanced techniques used by memory champions worldwide.',
    'programs.webinarBadge': 'Special Offer',
    'programs.webinarPerPass': '/ pass',
    'programs.webinarLink': 'View Webinar Syllabus & Details',
    'programs.mathTitle': 'Intellia 360° Mathematics Program',
    'programs.mathBadge': 'Flagship',
    'programs.mathShortDesc': 'Comprehensive conceptual mathematics curriculum focusing on first-principles understanding, logical rigor, and cognitive scaffolding.',
    'programs.mathPerTerm': '/ term',
    'programs.mathLink': 'Explore Full Mathematics Curriculum',
    'programs.flagshipTag': 'Flagship Academic Program',

    // Technology Section
    'tech.title': 'Technology That Supports Learning — Not Replaces It',
    'tech.subtitle': 'BrainSetu harmonizes physical mentorship with digital tools to deepen comprehension and practice consistency.',
    'tech.pillar1Title': 'Physical Learning',
    'tech.pillar1Desc': 'Expert mentor-led instruction, interactive Socratic discussions, and personal attention to build confidence.',
    'tech.pillar2Title': 'Digital Learning',
    'tech.pillar2Desc': 'Dynamic mathematics visualizations, interactive geometry tools, and gamified practice to make concepts intuitive.',
    'tech.pillar3Title': 'AI Support',
    'tech.pillar3Desc': 'Intelligent diagnostic assessments, personalized revision recommendations, and progress tracking.',
    'tech.keyCapabilities': 'Key Learning Capabilities:',
    'tech.feat1': 'Interactive learning',
    'tech.feat2': 'Digital practice',
    'tech.feat3': 'Gamification',
    'tech.feat4': 'Assessments',
    'tech.feat5': 'Progress tracking',
    'tech.feat6': 'Personalized practice',

    // Student Development Section
    'dev.title': 'Learning Beyond Marks',
    'dev.subtitle': 'We cultivate eight foundational cognitive and academic faculties that prepare students for lifetime intellectual growth.',
    'dev.outcome1Title': 'Memory',
    'dev.outcome1Desc': 'Concept chunking and structured recall techniques.',
    'dev.outcome2Title': 'Concentration',
    'dev.outcome2Desc': 'Sustained focus and selective attention stamina.',
    'dev.outcome3Title': 'Reasoning',
    'dev.outcome3Desc': 'Deductive inquiry and validation of logical steps.',
    'dev.outcome4Title': 'Creativity',
    'dev.outcome4Desc': 'Exploring multiple paths to solve complex problems.',
    'dev.outcome5Title': 'Problem-Solving',
    'dev.outcome5Desc': 'Heuristic toolkits to approach unfamiliar challenges.',
    'dev.outcome6Title': 'Logical Thinking',
    'dev.outcome6Desc': 'Sequential and algorithmic thought clarity.',
    'dev.outcome7Title': 'Academic Confidence',
    'dev.outcome7Desc': 'Poise and composure during rigorous examinations.',
    'dev.outcome8Title': 'Independent Learning',
    'dev.outcome8Desc': 'Autonomous study habits and metacognition.',

    // CTA Section
    'cta.title': 'A Brighter Learning Journey Starts Here',
    'cta.subtitle': 'Discover how your child approaches learning and identify foundational prerequisite gaps with a complimentary diagnostic consultation.',
    'cta.btn': 'Enquire Now',
    'cta.orCall': 'Or Call Direct:',
    'cta.address': '📍 Panvel Center: Feliz Flow Studio, Next to Hiranandani Trust School',
    'common.compareBtn': 'Compare Both Programs',

    // Modal / Welcome
    'welcome.newTitle': 'Welcome to BrainSetu Academy, {name}! 🎉',
    'welcome.newSubtitle': 'Your cognitive learning journey begins today. Unlock 10X Memory Power, master conceptual mathematics, and build lifelong thinking skills.',
    'welcome.returningTitle': 'Welcome back, {name}! 👋',
    'welcome.returningSubtitle': 'Your Neural Learning Bridge is active. Ready to conquer today’s missions and keep your learning streak going strong?',
    'welcome.newBadge': 'New Student Explorer',
    'welcome.returningBadge': 'Active Neural Learner',
    'welcome.startBtn': 'Start My Learning Missions 🚀',
    'welcome.resumeBtn': 'Resume Learning 🚀',
    'welcome.tip1': 'Interactive Simulators: Explore orbit mechanics, fractions, and spatial grids.',
    'welcome.tip2': 'Cognitive Retention: Reinforce memory pathways through spaced recall.',
    'welcome.streakLabel': 'Daily Streak Active',
    'welcome.xpLabel': 'Cognitive Sparks Earned',

    // Footer
    'footer.tagline': 'The Learning Bridge between Knowledge, Understanding, Application & Confidence.',
    'footer.quickLinks': 'Quick Navigation',
    'footer.programs': 'Our Programs',
    'footer.contact': 'Contact & Support',
    'footer.forParents': 'For Parents',
    'footer.studentDev': 'Student Development',
    'footer.contactEnquire': 'Contact / Enquire',
    'footer.portal': 'Student & Parent Portal',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.rights': 'All rights reserved. BrainSetu Academy.'
  },
  hi: {
    // Nav
    'nav.home': 'होम',
    'nav.programs': 'कार्यक्रम',
    'nav.contact': 'संपर्क',
    'nav.signIn': 'साइन इन',
    'nav.register': 'रजिस्टर',
    'nav.enquireNow': 'पूछताछ करें',
    'nav.menu': 'मेनू',
    'nav.logout': 'लॉग आउट',
    'nav.studentPortal': 'छात्र पोर्टल',
    'nav.learningLab': 'न्यूरल मेमोरी लैब',
    'nav.streak': 'स्ट्रीक',
    'nav.sparks': 'स्पार्क्स',
    'nav.days': 'दिन',

// Drawer & Navigation
    'nav.navigation': 'नेविगेशन',
    'nav.programsMasterclasses': 'कार्यक्रम और मास्टरक्लास',
    'nav.explore': 'ब्रेनसेतु को जानें',
    'nav.about': 'हमारे बारे में',
    'nav.aboutDesc': 'हमारा दृष्टिकोण, दर्शन और मिशन',
    'nav.approach': 'सीखने का दृष्टिकोण',
    'nav.approachDesc': '६-चरणीय महारत पद्धति',
    'nav.tech': 'प्रौद्योगिकी',
    'nav.techDesc': 'डिजिटल अभ्यास और इंटेलीया360 उपकरण',
    'nav.studentDev': 'छात्र विकास',
    'nav.studentDevDesc': 'संज्ञानात्मक कौशल और सर्वांगीण विकास',
    'nav.forParents': 'अभिभावकों के लिए',
    'nav.forParentsDesc': 'अभिभावक मार्गदर्शन और सीखने की कमियों का निदान',
    'nav.contactAdmissions': 'संपर्क और प्रवेश',
    'nav.contactDesc': 'डायग्नोस्टिक परामर्श निर्धारित करें',
    'nav.studentPortalDesc': 'न्यूरल मेमोरी लैब (मॉड्यूल 3) तक पहुंचने और प्रगति सहेजने के लिए साइन इन करें।',
    'nav.launchLab': 'न्यूरल मेमोरी लैब खोलें',
    'nav.bookConsultation': 'डायग्नोस्टिक परामर्श बुक करें',
    'nav.academyAddress': 'फेलिज फ्लो स्टूडियो, हीरानंदानी ट्रस्ट स्कूल के पास, पनवेल – 410207',
    'nav.privacyPolicy': 'गोपनीयता नीति',
    'nav.terms': 'नियम और शर्तें',

    // About Page
    'about.breadcrumb': 'हमारे बारे में',
    'about.heroTitle': 'ब्रेनसेतु अकादमी के बारे में',
    'about.heroDesc1': 'ब्रेनसेतु अकादमी एक आधुनिक शिक्षण और छात्र-विकास पहल है जिसे रटने की आदत और परीक्षा के तनाव को खत्म करने के लिए डिज़ाइन किया गया है।',
    'about.heroDesc2': '"सेतु" का अर्थ है पुल। ब्रेनसेतु बौद्धिक और मनोवैज्ञानिक सेतु का प्रतीक है जो जोड़ता है:',
    'about.bridgeKnowledge': 'ज्ञान (Knowledge)',
    'about.bridgeMemory': 'स्मरण (Memory)',
    'about.bridgeConcepts': 'अवधारणा (Concepts)',
    'about.bridgeApplication': 'अनुप्रयोग (Application)',
    'about.bridgePotential': 'क्षमता (Potential)',
    'about.philosophyTitle': 'हमारा दर्शन',
    'about.philosophyDesc': 'हम निडर, आत्मविश्वासी और आजीवन सीखने वाले विचारक तैयार करने के लिए मूल गणितीय तर्क, स्मृति तकनीकों और सहानुभूतिपूर्ण मेंटरशिप को जोड़ते हैं।',

    // Learning Approach Page
    'approach.breadcrumb': 'सीखने का दृष्टिकोण',
    'approach.heroTitle': 'ब्रेनसेतु शिक्षण दृष्टिकोण',
    'approach.heroSubtitle': 'संरचित संज्ञानात्मक प्रगति और वैज्ञानिक मेमोरी एन्कोडिंग के माध्यम से यांत्रिक रटने से स्थायी समझ की ओर बढ़ना।',
    'approach.stepTitle': 'छह-चरणीय महारत प्रगति',
    'approach.stepSubtitle': 'प्रत्येक अवधारणा को एक उद्देश्यपूर्ण क्रम के माध्यम से सिखाया जाता है जो कठिन अनुप्रयोगों से पहले सहज स्पष्टता का निर्माण करता है।',

    // Technology Page
    'technology.breadcrumb': 'प्रौद्योगिकी और एआई',
    'technology.heroTitle': 'प्रौद्योगिकी जो मानवीय समझ को सशक्त बनाती है',
    'technology.heroSubtitle': 'हमारा मानना है कि तकनीक को कभी भी एक मार्गदर्शक की सहानुभूति और अंतर्दृष्टि का स्थान नहीं लेना चाहिए। इसके बजाय, यह गणित को दृश्यमान और समझने योग्य बनाने में मदद करती है।',
    'technology.exploreBtn': 'कार्यक्रम देखें',
    'technology.enquireBtn': 'डायग्नोस्टिक मूल्यांकन बुक करें',

    // Student Development Page
    'studentDev.breadcrumb': 'छात्र विकास',
    'studentDev.heroTitle': 'समग्र विचारक का विकास',
    'studentDev.heroSubtitle': 'संज्ञानात्मक कौशल, भावनात्मक स्थिरता और सीखने के अनुशासन जो बोर्ड परीक्षाओं और परीक्षणों से परे आजीवन बने रहते हैं।',
    'studentDev.outcomesTitle': 'आठ मूलभूत संज्ञानात्मक परिणाम',
    'studentDev.outcomesSubtitle': 'प्रत्येक छात्र ब्रेनसेतु के साथ अपनी यात्रा के दौरान इन महत्वपूर्ण संज्ञानात्मक क्षमताओं को विकसित करता है।',

    // Parents Page
    'parents.breadcrumb': 'अभिभावकों के लिए',
    'parents.heroTitle': 'अभिभावकों को समझना कि उनका बच्चा कैसे सीखता है',
    'parents.heroSubtitle': 'गणित का डर बुद्धि की कमी नहीं है; यह हमेशा किसी पिछली अवधारणा की अस्पष्टता या रटने के तरीके के कारण होता है। हम माता-पिता को स्पष्टता और मार्गदर्शन प्रदान करते हैं।',
    'parents.bookBtn': 'काउंसलिंग / मूल्यांकन पूछताछ बुक करें',
    'parents.exploreBtn': 'अनुशंसित पाठ्यक्रम देखें',

    // Contact Page
    'contact.breadcrumb': 'संपर्क और प्रवेश',
    'contact.heroTitle': 'संपर्क और डायग्नोस्टिक प्रवेश',
    'contact.heroSubtitle': 'अपने बच्चे के लिए 1-ऑन-1 डायग्नोस्टिक परामर्श के लिए हमारे वरिष्ठ शिक्षकों से बात करें या हमारे पनवेल केंद्र पर आएं।',
    'contact.addressTitle': 'पनवेल शिक्षण केंद्र',
    'contact.hoursTitle': 'कार्य समय',
    'contact.hoursDesc': 'सोमवार - शनिवार: सुबह 10:00 - शाम 7:30',
    'contact.phoneTitle': 'फोन और व्हाट्सएप',
    'contact.formTitle': 'डायग्नोस्टिक परामर्श बुक करें',
    'contact.formSubtitle': 'नीचे दिया गया फॉर्म भरें और हमारे शैक्षणिक सलाहकार २४ घंटे के भीतर आपसे संपर्क करेंगे।',

    'about.visionBadge': 'हमारा दृष्टिकोण',
    'about.visionQuote': 'शिक्षार्थियों की ऐसी पीढ़ी तैयार करना जो जानकारी को केवल याद न रखे, बल्कि ज्ञान को गहराई से समझे, बनाए रखे, लागू करे और आत्मविश्वास से उपयोग करे।',
    'about.philosophyBadge': 'मार्गदर्शक सिद्धांत',
    'about.philosophyHeading': 'हमारा दर्शन',
    'about.philosophyQuote': '“सीखने से समझ पैदा होनी चाहिए, केवल स्मरण नहीं।”',
    'about.activePartTitle': 'सक्रिय भागीदारी',
    'about.activePartDesc': 'छात्रों को अपनी सीखने की यात्रा में सक्रिय रूप से भाग लेना चाहिए—सूत्रों को केवल रटने के बजाय सवाल पूछना, प्रयोग करना, निष्कर्ष निकालना और उनका बचाव करना।',
    'about.holisticDevTitle': 'समग्र विकास',
    'about.holisticDevDesc': 'शैक्षणिक प्रदर्शन और आजीवन संज्ञानात्मक कौशल एक साथ विकसित होने चाहिए। परीक्षा में अच्छे अंक वास्तविक बौद्धिक महारत का स्वाभाविक परिणाम हैं।',
    'about.missionBadge': 'उद्देश्य एवं कार्य',
    'about.missionTitle': 'हमारा आठ-चरणीय मिशन',
    'about.missionSubtitle': 'वे विशिष्ट, मापने योग्य प्रतिबद्धताएं जो हमारे पाठ्यक्रम, मेंटरशिप और तकनीक को दिशा देती हैं।',
    'about.corePillar': 'मुख्य स्तंभ',
    'about.mission1Title': 'स्मृति और प्रतिधारण में सुधार',
    'about.mission1Desc': 'अस्थायी रटने की आदत को स्थायी अर्थपूर्ण मेमोरी तकनीकों से बदलें।',
    'about.mission2Title': 'तार्किक और विश्लेषणात्मक सोच का विकास',
    'about.mission2Desc': 'संरचित निगमनात्मक तर्क और चरणबद्ध एल्गोरिदम स्पष्टता का निर्माण करें।',
    'about.mission3Title': 'शैक्षणिक बुनियादी बातों को मजबूत करना',
    'about.mission3Desc': 'पिछली वैचारिक कमियों को दूर करें ताकि उच्च गणित पूरी तरह से सहज बन जाए।',
    'about.mission4Title': 'सीखने को आकर्षक और रोचक बनाना',
    'about.mission4Desc': 'कठिन समीकरणों को संवादात्मक, दृश्य खोजों और गणितीय पहेलियों में बदलें।',
    'about.mission5Title': 'रटने की पद्धति को कम करना',
    'about.mission5Desc': 'मूल सिद्धांतों की समझ को बढ़ावा दें: याद करने से पहले सिद्ध करें और कल्पना करें।',
    'about.mission6Title': 'शैक्षणिक आत्मविश्वास का निर्माण',
    'about.mission6Desc': 'जटिल और गैर-पारंपरिक चुनौतियों का सामना करते समय निडरता और धैर्य विकसित करें।',
    'about.mission7Title': 'व्यक्तिगत शैक्षणिक मार्गदर्शन',
    'about.mission7Desc': 'प्रत्येक छात्र की व्यक्तिगत सीखने की गति के अनुसार समर्पित मेंटर सहायता।',
    'about.mission8Title': 'आधुनिक प्रौद्योगिकी का समावेश',
    'about.mission8Desc': 'अनुभवी मानवीय मेंटरशिप को भविष्य के लिए तैयार इंटेलीया360 उपकरणों से जोड़ें।',
    'whoWeServe.badge': 'विकासात्मक चरण',
    'whoWeServe.title': 'हर चरण के लिए विशेष रूप से डिज़ाइन की गई शिक्षा',
    'whoWeServe.subtitle': 'खेल-आधारित पैटर्न पहचान से लेकर उन्नत प्रतिस्पर्धी ओलंपियाड प्रमाणों तक, हमारा पाठ्यक्रम हर पड़ाव के अनुकूल है।',
    'whoWeServe.exploreBtn': 'चरणवार पाठ्यक्रम देखें',
    'whoWeServe.stage1Stage': 'प्री-प्राइमरी',
    'whoWeServe.stage1Age': 'आयु 4 – 6 वर्ष',
    'whoWeServe.stage1Headline': 'जिज्ञासा और मूलभूत सोच',
    'whoWeServe.stage1Desc': 'मजेदार बहु-संवेदी खेलों के माध्यम से प्रारंभिक संख्या बोध, स्थानिक जागरूकता और सहज पैटर्न पहचान का पोषण करें।',
    'whoWeServe.stage1Badge': 'आरंभिक अन्वेषक',
    'whoWeServe.stage2Stage': 'प्राइमरी',
    'whoWeServe.stage2Age': 'कक्षा 1 – 5',
    'whoWeServe.stage2Headline': 'मजबूत गणितीय आधार',
    'whoWeServe.stage2Desc': 'बुनियादी अंकगणित को ठोस वैचारिक आधार में बदलें, गणित के डर को जड़ पकड़ने से पहले ही समाप्त करें।',
    'whoWeServe.stage2Badge': 'मूल आधार',
    'whoWeServe.stage3Stage': 'मिडिल स्कूल',
    'whoWeServe.stage3Age': 'कक्षा 6 – 8',
    'whoWeServe.stage3Headline': 'संकल्पनात्मक समझ और तर्क',
    'whoWeServe.stage3Desc': 'अंकों को बीजगणितीय अमूर्तता, ज्यामितीय तर्क और संज्ञानात्मक मेमोरी तकनीकों से जोड़ें।',
    'whoWeServe.stage3Badge': 'कॉन्सेप्ट बिल्डर्स',
    'whoWeServe.stage4Stage': 'माध्यमिक (सेकेंडरी)',
    'whoWeServe.stage4Age': 'कक्षा 9 – 10',
    'whoWeServe.stage4Headline': 'शैक्षणिक महारत और समस्या समाधान',
    'whoWeServe.stage4Desc': 'बोर्ड परीक्षा पाठ्यक्रम, व्यवस्थित परीक्षा निष्पादन, बहु-चरणीय प्रमाण और उच्च-स्तरीय सोच में महारत हासिल करें।',
    'whoWeServe.stage4Badge': 'बोर्ड उत्कृष्टता',
    'whoWeServe.stage5Stage': 'उच्चतर माध्यमिक',
    'whoWeServe.stage5Age': 'कक्षा 11 – 12',
    'whoWeServe.stage5Headline': 'उन्नत गणितीय और प्रतियोगी आधार',
    'whoWeServe.stage5Desc': 'ओलंपियाड प्रमाण विधियों, उन्नत कैलकुलस और गहन विश्लेषणात्मक समस्या समाधान से लैस करें।',
    'whoWeServe.stage5Badge': 'प्रतियोगी बढ़त',
    'parents.pillarsBadge': 'अभिभावक सशक्तिकरण',
    'parents.pillarsTitle': 'हमारे अभिभावक मार्गदर्शन के पांच स्तंभ',
    'parents.pillarsSubtitle': 'वे ठोस तरीके जिनसे हम माता-पिता को सूचित, समर्थित और बच्चे की पढ़ाई में आत्मविश्वासी रखते हैं।',
    'parents.pillar1Title': 'सीखने की शैली को समझें',
    'parents.pillar1Desc': 'जानें कि आपका बच्चा स्थानिक, मौखिक और संख्यात्मक अवधारणाओं को कैसे समझता है ताकि बिना तनाव के उनका समर्थन किया जा सके।',
    'parents.pillar2Title': 'छुपी हुई सीखने की कमियों को पहचानें',
    'parents.pillar2Desc': 'पिछली कक्षाओं की उन मूलभूत भ्रांतियों को पहचानें जो वर्तमान में गणित के डर का कारण बनती हैं।',
    'parents.pillar3Title': 'समग्र संज्ञानात्मक विकास को ट्रैक करें',
    'parents.pillar3Desc': 'एकाग्रता अवधि, कार्यशील स्मृति प्रतिधारण और स्वतंत्र समस्या समाधान के ठोस संकेतकों की निगरानी करें।',
    'parents.pillar4Title': 'मेंटरशिप परामर्श और अपडेट',
    'parents.pillar4Desc': 'पारदर्शी, व्यावहारिक प्रतिक्रिया और समर्पित शिक्षकों से सीधा संवाद प्राप्त करें।',
    'parents.pillar5Title': 'घर पर अध्ययन की बेहतर आदतें बनाएं',
    'parents.pillar5Desc': 'गृहकार्य के समय को एक सुखद, तनावमुक्त और आत्मविश्वास से भरी आदत में बदलने के व्यावहारिक उपाय।',
    'parents.journeyBadge': 'अभिभावक यात्रा',
    'parents.journeyTitle': '७-चरणीय अभिभावक साझेदारी यात्रा',
    'parents.journeySubtitle': 'आरंभिक डायग्नोस्टिक पूछताछ से लेकर दीर्घकालिक बौद्धिक विकास तक परिवारों का मार्गदर्शन।',
    'approach.methodBadge': 'प्रगति ढांचा',
    'approach.methodTitle': 'छह-चरणीय महारत प्रगति',
    'approach.methodSubtitle': 'प्रत्येक अवधारणा को एक उद्देश्यपूर्ण क्रम के माध्यम से सिखाया जाता है जो जटिल अनुप्रयोगों से पहले सहज स्पष्टता का निर्माण करता है।',
    'approach.stepFocus': 'केंद्र बिंदु:',
    'approach.stepBridge': 'सेतु:',
    'approach.techBadge': 'संज्ञानात्मक विज्ञान कार्य में',
    'approach.techTitle': 'छह संज्ञानात्मक तकनीकें',
    'approach.techSubtitle': 'वैज्ञानिक स्मरण उपकरण जो परीक्षा के दबाव में भी याददाश्त को सहज और विश्वसनीय बनाते हैं।',
    'approach.techHow': 'यह कैसे काम करता है:',
    'approach.techExample': 'कक्षा का उदाहरण:',
    'approach.tech1Name': 'संकल्पना चंकिंग (Concept Chunking)',
    'approach.tech1Desc': 'जटिल सूत्रों और अवधारणाओं को सुसंगत मानसिक पैकेटों में विभाजित करना।',
    'approach.tech1How': 'हमारी कार्यशील स्मृति एक समय में ४-७ टुकड़ों को संभाल सकती है। लंबे प्रमाणों को ३ मुख्य चरणों में व्यवस्थित करके छात्र आसानी से सीखते हैं।',
    'approach.tech1Example': 'बहुपद गुणनखंडन को ३ चरणों में बांटना: सामान्य पद -> पैटर्न पहचान -> मध्य-पद विभाजन।',
    'approach.tech2Name': 'तार्किक संबंध (Logical Connections)',
    'approach.tech2Desc': 'नए विषयों को पहले से सीखी गई बुनियादी अवधारणाओं से जोड़ना।',
    'approach.tech2How': 'मस्तिष्क जुड़ाव से याद रखता है। जब छात्र देखते हैं कि निर्देशांक ज्यामिति केवल बीजगणित और ज्यामिति का मिलन है, तो वे इसे आसानी से समझ जाते हैं।',
    'approach.tech2Example': 'पायथागोरस प्रमेय को सीधे दूरी सूत्र और वृत्त के समीकरणों से जोड़ना।',
    'approach.tech3Name': 'सक्रिय स्मरण अभ्यास (Active Retrieval)',
    'approach.tech3Desc': 'नियमित आत्म-परीक्षण के माध्यम से न्यूरल कनेक्शन को मजबूत करना।',
    'approach.tech3How': 'किताब पढ़ने से ज्ञान का भ्रम होता है। किताब बंद करके सूत्र के पीछे के तर्क को खुद से लिखना स्मृति को स्थायी बनाता है।',
    'approach.tech3Example': '५ मिनट की त्वरित चुनौतियां जहां छात्र सूत्र के तर्क को शुरू से लिखते हैं।',
    'approach.tech4Name': 'दृश्य जुड़ाव (Visual Associations)',
    'approach.tech4Desc': 'अमूर्त प्रतीकों को जीवंत स्थानिक और दृश्य रूपों में बदलना।',
    'approach.tech4How': 'दृश्य प्रसंस्करण बहुत तेज और स्थायी होता है। हम छात्रों को समीकरणों को ज्यामितीय परिवर्तनों और तराजू के रूप में देखना सिखाते हैं।',
    'approach.tech4Example': 'समीकरणों को एक संतुलित तराजू के रूप में देखना जहां दोनों तरफ समान क्रियाएं की जाती हैं।',
    'approach.tech5Name': 'पैटर्न पहचान (Pattern Recognition)',
    'approach.tech5Desc': 'विभिन्न समस्याओं में अंतर्निहित समान संरचनाओं को पहचानना।',
    'approach.tech5How': 'गणितज्ञ हजारों अलग सवाल नहीं करते; वे पैटर्न पहचानते हैं। हम छात्रों को मुख्य रूपांकनों को पहचानना सिखाते हैं।',
    'approach.tech5Example': 'अनुक्रमों और बीजगणितीय व्यंजकों में समरूपता की पहचान करना।',
    'approach.tech6Name': 'संरचित अंतराल दोहराव (Spaced Revision)',
    'approach.tech6Desc': 'वैज्ञानिक रूप से निर्धारित समय अंतरालों पर अवधारणाओं का पुनरीक्षण।',
    'approach.tech6How': 'भूलने की प्राकृतिक प्रवृत्ति को हराना। दिन १, ३, ७ और २१ पर पुनरीक्षण करने से स्मृति का क्षय लगभग शून्य हो जाता है।',
    'approach.tech6Example': 'स्मृति क्षीण होने के समय पर निर्धारित १० मिनट का त्वरित पुनरावलोकन।',
    'technology.pillarsBadge': 'एकीकृत माध्यम',
    'technology.pillarsTitle': 'ब्रेनसेतु अनुभव के तीन मुख्य स्तंभ',
    'technology.pillarsSubtitle': 'प्रत्येक माध्यम छात्र की बौद्धिक यात्रा को आकार देने में एक विशिष्ट और महत्वपूर्ण भूमिका निभाता है।',
    'technology.pillar1Title': 'प्रत्यक्ष शिक्षण (Physical Learning)',
    'technology.pillar1Tag': 'मानवीय मेंटर संपर्क',
    'technology.pillar1Desc': 'आत्मविश्वास बढ़ाने के लिए विशेषज्ञ शिक्षकों के नेतृत्व में मार्गदर्शन, संवादात्मक चर्चा और व्यक्तिगत ध्यान।',
    'technology.pillar2Title': 'डिजिटल शिक्षण (Digital Learning)',
    'technology.pillar2Tag': 'संवादात्मक सॉफ्टवेयर और दृश्य',
    'technology.pillar2Desc': 'गतिशील गणितीय व्हिज्युअलायझेशन, इंटरैक्टिव ज्यामिति उपकरण और खेल-आधारित अभ्यास जो अवधारणाओं को सहज बनाते हैं।',
    'technology.pillar3Title': 'एआई-संचालित डायग्नोस्टिक्स',
    'technology.pillar3Tag': 'इंटेलीया360 लर्निंग इंजन',
    'technology.pillar3Desc': 'बुद्धिमान डायग्नोस्टिक मूल्यांकन, व्यक्तिगत पुनरीक्षण सिफारिशें और विस्तृत प्रगति ट्रैकिंग।',
    'technology.featuresBadge': 'डिजिटल बुद्धिमत्ता',
    'technology.featuresTitle': 'भविष्य के लिए तैयार इंटेलीया360 इकोसिस्टम',
    'technology.featuresSubtitle': 'छात्र अभ्यास, डायग्नोस्टिक मूल्यांकन और विश्लेषणात्मक प्रतिक्रिया को जोड़ने वाला शक्तिशाली सॉफ्टवेयर इंजन।',
    'studentDev.pillarsBadge': 'संज्ञानात्मक वर्गीकरण',
    'studentDev.pillarsTitle': 'विद्यार्थी विकास के नौ मुख्य स्तंभ',
    'studentDev.pillarsSubtitle': 'ब्रेनसेतु अकादमी में उपयोग किए जाने वाले संज्ञानात्मक तंत्र और शैक्षणिक अभ्यासों को जानने के लिए प्रत्येक कौशल पर क्लिक करें।',
    'studentDev.mechanismLabel': 'संज्ञानात्मक तंत्र:',
    'studentDev.drillLabel': 'ब्रेनसेतु शैक्षणिक अभ्यास:',
    'studentDev.outcomeLabel': 'मापने योग्य परिणाम:',
    'studentDev.trackingTitle': 'डायग्नोस्टिक एनालिटिक्स डैशबोर्ड पूर्वावलोकन',
    'studentDev.trackingSubtitle': 'अभ्यास सत्रों में संज्ञानात्मक सहनशक्ति और गणितीय स्मरण शक्ति की वास्तविक समय में निगरानी।',
    'contact.formHeading': 'परामर्श का समय निर्धारित करें',
    'contact.formSub': 'नीचे दिया गया फॉर्म भरें और हमारी शैक्षणिक टीम २४ घंटे के भीतर आपसे संपर्क करेगी।',
    'contact.nameLabel': 'अभिभावक / छात्र का पूरा नाम',
    'contact.namePlaceholder': 'उदा. रमेश शर्मा',
    'contact.gradeLabel': 'छात्र की कक्षा / ग्रेड',
    'contact.gradePlaceholder': 'उदा. कक्षा 7, CBSE / ICSE',
    'contact.phoneLabel': 'मोबाइल नंबर / व्हाट्सएप',
    'contact.phonePlaceholder': '+91 98765 43210',
    'contact.emailLabel': 'ईमेल पता',
    'contact.emailPlaceholder': 'parent@example.com',
    'contact.programLabel': 'रुचि का कार्यक्रम',
    'contact.methodLabel': 'पसंदीदा संपर्क माध्यम',
    'contact.messageLabel': 'संदेश / सीखने में विशेष चुनौतियाँ (वैकल्पिक)',
    'contact.messagePlaceholder': 'बताएं कि आपके बच्चे को किन अवधारणाओं में कठिनाई होती है...',
    'contact.submitBtn': 'डायग्नोस्टिक पूछताछ सबमिट करें',
    'contact.submittingBtn': 'सबमिट हो रहा है...',
    'contact.privacyNotice': 'हम परिवार की गोपनीयता का सम्मान करते हैं। आपकी संपर्क जानकारी पूर्णतः गोपनीय है।',

    // Hero
    'hero.badge': 'अग्रणी संज्ञानात्मक और गणित अकादमी',
    'hero.titleLine1': 'स्मार्ट दिमाग का निर्माण।',
    'hero.titleLine2': 'आत्मविश्वासी शिक्षार्थी बनाना।',
    'hero.subtitle': 'तेजी से सीखें, बेहतर याद रखें, समझदारी से सोचें और आत्मविश्वास के साथ प्रदर्शन करें। ब्रेनसेतु ज्ञान → समझ → अनुप्रयोग → आत्मविश्वास के बीच का सेतु है।',
    'hero.exploreBtn': 'कार्यक्रम देखें',
    'hero.enquireBtn': 'पूछताछ करें',
    'hero.statStudents': '10,000+ छात्र प्रशिक्षित',
    'hero.statRetention': '10X स्मरण शक्ति',
    'hero.statConfidence': '98% गणित में आत्मविश्वास',

    // Impact Section
    'impact.badge': 'हमारा प्रभाव',
    'impact.title': 'उत्कृष्टता का प्रमाणित रिकॉर्ड',
    'impact.subtitle': 'अनुसंधान-आधारित संज्ञानात्मक और संकल्पनात्मक शिक्षण पद्धतियों के साथ देश भर के छात्रों, शिक्षकों और स्कूलों को सशक्त बनाना।',
    'impact.stat1Label': 'सफल पंजीकरण',
    'impact.stat2Label': 'सक्रिय सदस्य',
    'impact.stat3Label': 'वर्षों का अनुभव',
    'impact.stat4Label': 'लाइव वेबिनार',
    'impact.stat5Label': 'सेमिनार और कार्यशालाएं',
    'impact.stat6Label': 'संबद्ध विद्यालय',

    // Why BrainSetu Section
    'why.title': 'सिर्फ पढ़ाई से कहीं अधिक',
    'why.subtitle': 'ब्रेनसेतु गणित, संज्ञानात्मक विकास, मेमोरी तकनीक, मेंटरशिप और तकनीक को जोड़कर एक गहरा और सार्थक शिक्षण अनुभव प्रदान करता है।',
    'why.benefit1Title': 'संकल्पनात्मक शिक्षा',
    'why.benefit1Desc': 'गणितीय सूत्रों को रटने के बजाय उनके पीछे के "क्यों" और तार्किक संबंधों को गहराई से समझें।',
    'why.benefit2Title': 'तार्किक सोच',
    'why.benefit2Desc': 'संरचित विश्लेषण, पैटर्न पहचान और विश्लेषणात्मक स्पष्टता विकसित करें जो हर विषय में काम आए।',
    'why.benefit3Title': 'मेमोरी तकनीक',
    'why.benefit3Desc': 'वैज्ञानिक संकल्पना चंकिंग और सक्रिय स्मरण विधियाँ जो दीर्घकालिक याददाश्त को तनावमुक्त बनाती हैं।',
    'why.benefit4Title': 'समस्या समाधान और तकनीक',
    'why.benefit4Desc': 'आधुनिक डिजिटल गणित शिक्षण उपकरणों द्वारा समर्थित स्वतंत्र समस्या-समाधान कौशल।',

    // Video Showcase Section
    'video.badge': 'आधिकारिक वीडियो प्रस्तुति',
    'video.title': 'ब्रेनसेतु को कार्य में देखें',
    'video.subtitle': 'देखें कि कैसे हमारी संज्ञानात्मक विकास पद्धति और इंटेलीया 360 प्रोग्राम छात्रों में गणितीय स्पष्टता, तार्किक सोच और आजीवन आत्मविश्वास का निर्माण करते हैं।',
    'video.feat1Title': 'संकल्पनात्मक स्पष्टता',
    'video.feat1Desc': 'मूल सिद्धांतों पर आधारित गणितीय तर्क जो रटने की आदत को समाप्त करता है।',
    'video.feat2Title': '10X स्मरण तकनीक',
    'video.feat2Desc': 'वैज्ञानिक संकल्पना चंकिंग और न्यूरल रिकॉल तकनीकें।',
    'video.feat3Title': 'विशेषज्ञ मेंटरशिप',
    'video.feat3Desc': 'अनुकूली डिजिटल अभ्यास उपकरणों के साथ समर्पित मार्गदर्शक।',
    'video.watchYoutube': 'यूट्यूब पर सीधे देखें',

    // Learning Journey Section
    'journey.title': 'सीखने की यात्रा',
    'journey.subtitle': 'एक स्पष्ट छह-चरणीय संज्ञानात्मक प्रगति जो नई अवधारणाओं को स्थायी समझ और महारत में बदलती है।',
    'journey.stage': 'चरण',
    'journey.step1Title': 'सीखें (Learn)',
    'journey.step1Desc': 'सहज अंतर्दृष्टि और वास्तविक दुनिया की जिज्ञासा के साथ अवधारणा का परिचय।',
    'journey.step2Title': 'समझें (Understand)',
    'journey.step2Desc': 'मूल सिद्धांतों के आधार पर अवधारणात्मक स्पष्टता का निर्माण।',
    'journey.step3Title': 'याद रखें (Remember)',
    'journey.step3Desc': 'मेमोरी तकनीकों और न्यूरल संबंधों का उपयोग करके याददाश्त मजबूत करें।',
    'journey.step4Title': 'अभ्यास (Practice)',
    'journey.step4Desc': 'सोचे-समझे, श्रेणीबद्ध अभ्यास सेटों के माध्यम से सुदृढ़ करें।',
    'journey.step5Title': 'लागू करें (Apply)',
    'journey.step5Desc': 'कठिन समस्याओं और वास्तविक जीवन स्थितियों में ज्ञान का उपयोग करें।',
    'journey.step6Title': 'महारत (Master)',
    'journey.step6Desc': 'प्रगति को ट्रैक करें, कमियों को दूर करें और स्थायी महारत हासिल करें।',

    // Programs Section
    'programs.sectionBadge': 'संज्ञानात्मक और गणित मार्ग',
    'programs.sectionTitle': 'स्मार्ट सीखने के लिए डिज़ाइन किए गए कार्यक्रम',
    'programs.sectionSubtitle': 'हमारी विशेष मेमोरी मास्टरक्लास और प्रमुख वैचारिक गणित पाठ्यक्रम में से चुनें।',
    'programs.enquireBtn': 'पूछताछ करें और डायग्नोस्टिक बुक करें',
    'programs.original': 'मूल्य:',
    'programs.webinarTitle': '10X मेमोरी पावर वेबिनार',
    'programs.webinarShortDesc': 'अपनी स्मरण शक्ति को 10 गुना बढ़ाने के लिए चरण-दर-चरण पाठ्यक्रम। विश्वभर के मेमोरी चैंपियनों द्वारा उपयोग की जाने वाली तकनीकों को सीखें।',
    'programs.webinarBadge': 'विशेष ऑफर',
    'programs.webinarPerPass': '/ पास',
    'programs.webinarLink': 'वेबिनार विवरण और पाठ्यक्रम देखें',
    'programs.mathTitle': 'इंटेलेलिया 360° गणित कार्यक्रम',
    'programs.mathBadge': 'फ्लैगशिप',
    'programs.mathShortDesc': 'मूल सिद्धांतों की समझ, तार्किक विश्लेषण और संज्ञानात्मक विकास पर केंद्रित व्यापक वैचारिक गणित पाठ्यक्रम।',
    'programs.mathPerTerm': '/ सत्र',
    'programs.mathLink': 'संपूर्ण गणित पाठ्यक्रम देखें',
    'programs.flagshipTag': 'प्रमुख शैक्षणिक कार्यक्रम',

    // Technology Section
    'tech.title': 'सीखने में सहायक तकनीक — विकल्प नहीं',
    'tech.subtitle': 'ब्रेनसेतु समझ को गहरा करने और नियमित अभ्यास के लिए व्यक्तिगत मेंटरशिप को डिजिटल उपकरणों के साथ जोड़ता है।',
    'tech.pillar1Title': 'प्रत्यक्ष शिक्षण (Physical Learning)',
    'tech.pillar1Desc': 'आत्मविश्वास बढ़ाने के लिए विशेषज्ञ शिक्षकों द्वारा मार्गदर्शन, संवादात्मक चर्चा और व्यक्तिगत ध्यान।',
    'tech.pillar2Title': 'डिजिटल शिक्षण (Digital Learning)',
    'tech.pillar2Desc': 'अवधारणाओं को सहज बनाने के लिए गतिशील गणितीय विज़ुअलाइज़ेशन और गेम-आधारित अभ्यास।',
    'tech.pillar3Title': 'एआई सहायता (AI Support)',
    'tech.pillar3Desc': 'बुद्धिमान डायग्नोस्टिक मूल्यांकन, व्यक्तिगत संशोधन सिफारिशें और प्रगति ट्रैकिंग।',
    'tech.keyCapabilities': 'प्रमुख शिक्षण क्षमताएं:',
    'tech.feat1': 'इंटरैक्टिव लर्निंग',
    'tech.feat2': 'डिजिटल अभ्यास',
    'tech.feat3': 'गेमिफिकेशन',
    'tech.feat4': 'मूल्यांकन',
    'tech.feat5': 'प्रगति ट्रैकिंग',
    'tech.feat6': 'व्यक्तिगत अभ्यास',

    // Student Development Section
    'dev.title': 'अंकों से परे वास्तविक शिक्षा',
    'dev.subtitle': 'हम आठ मूलभूत संज्ञानात्मक और शैक्षणिक क्षमताओं को विकसित करते हैं जो छात्रों को जीवन भर बौद्धिक विकास के लिए तैयार करती हैं।',
    'dev.outcome1Title': 'स्मरण शक्ति (Memory)',
    'dev.outcome1Desc': 'संकल्पना चंकिंग और संरचित स्मरण तकनीक।',
    'dev.outcome2Title': 'एकाग्रता (Concentration)',
    'dev.outcome2Desc': 'लगातार ध्यान केंद्रित करने और एकाग्रता बनाए रखने की क्षमता।',
    'dev.outcome3Title': 'तर्क क्षमता (Reasoning)',
    'dev.outcome3Desc': 'तार्किक जांच और तार्किक कदमों का सत्यापन।',
    'dev.outcome4Title': 'रचनात्मकता (Creativity)',
    'dev.outcome4Desc': 'जटिल समस्याओं को हल करने के लिए कई रास्ते तलाशना।',
    'dev.outcome5Title': 'समस्या समाधान (Problem-Solving)',
    'dev.outcome5Desc': 'अपरिचित चुनौतियों से निपटने के लिए ह्यूरिस्टिक टूलकिट।',
    'dev.outcome6Title': 'तार्किक सोच (Logical Thinking)',
    'dev.outcome6Desc': 'क्रमबद्ध और एल्गोरिथम विचार स्पष्टता।',
    'dev.outcome7Title': 'शैक्षणिक आत्मविश्वास (Academic Confidence)',
    'dev.outcome7Desc': 'कठिन परीक्षाओं के दौरान धैर्य, संतुलन और आत्मविश्वास।',
    'dev.outcome8Title': 'स्वतंत्र अध्ययन (Independent Learning)',
    'dev.outcome8Desc': 'स्वायत्त अध्ययन की आदतें और आत्म-चिंतन।',

    // CTA Section
    'cta.title': 'एक उज्जवल शिक्षण यात्रा यहाँ से शुरू होती है',
    'cta.subtitle': 'जानें कि आपका बच्चा कैसे सीखता है और हमारे मानार्थ डायग्नोस्टिक परामर्श के साथ बुनियादी कमियों की पहचान करें।',
    'cta.btn': 'पूछताछ करें',
    'cta.orCall': 'या सीधे कॉल करें:',
    'cta.address': '📍 पनवेल केंद्र: फेलिज़ फ्लो स्टूडियो, हीरानंदानी ट्रस्ट स्कूल के पास',
    'common.compareBtn': 'दोनों कार्यक्रमों की तुलना करें',

    // Modal / Welcome
    'welcome.newTitle': 'ब्रेनसेतु अकादमी में आपका स्वागत है, {name}! 🎉',
    'welcome.newSubtitle': 'आपकी संज्ञानात्मक सीखने की यात्रा आज से शुरू हो रही है। 10X मेमोरी पावर अनलॉक करें और वैचारिक गणित में महारत हासिल करें।',
    'welcome.returningTitle': 'वापसी पर स्वागत है, {name}! 👋',
    'welcome.returningSubtitle': 'आपका न्यूरल लर्निंग ब्रिज सक्रिय है। आज के मिशन पूरे करने और अपनी सीखने की स्ट्रीक जारी रखने के लिए तैयार हैं?',
    'welcome.newBadge': 'नया छात्र अन्वेषक',
    'welcome.returningBadge': 'सक्रिय न्यूरल शिक्षार्थी',
    'welcome.startBtn': 'सीखने का मिशन शुरू करें 🚀',
    'welcome.resumeBtn': 'सीखना जारी रखें 🚀',
    'welcome.tip1': 'इंटरैक्टिव सिमुलेटर: कक्षा यांत्रिकी, भिन्न और स्थानिक ग्रिड का अन्वेषण करें।',
    'welcome.tip2': 'संज्ञानात्मक प्रतिधारण: स्मरण शक्ति को मजबूत करें।',
    'welcome.streakLabel': 'दैनिक स्ट्रीक सक्रिय',
    'welcome.xpLabel': 'संज्ञानात्मक स्पार्क्स अर्जित',

    // Footer
    'footer.tagline': 'ज्ञान, समझ, अनुप्रयोग और आत्मविश्वास के बीच का सीखने का सेतु।',
    'footer.quickLinks': 'त्वरित नेविगेशन',
    'footer.programs': 'हमारे कार्यक्रम',
    'footer.contact': 'संपर्क और सहायता',
    'footer.forParents': 'अभिभावकों के लिए',
    'footer.studentDev': 'छात्र विकास',
    'footer.contactEnquire': 'संपर्क / पूछताछ',
    'footer.portal': 'छात्र और अभिभावक पोर्टल',
    'footer.privacy': 'गोपनीयता नीति',
    'footer.terms': 'नियम और शर्तें',
    'footer.rights': 'सर्वाधिकार सुरक्षित। ब्रेनसेतु अकादमी।'
  },
  mr: {
    // Nav
    'nav.home': 'मुख्यपृष्ठ',
    'nav.programs': 'अभ्यासक्रम',
    'nav.contact': 'संपर्क',
    'nav.signIn': 'साइन इन',
    'nav.register': 'नोंदणी करा',
    'nav.enquireNow': 'चौकशी करा',
    'nav.menu': 'मेनू',
    'nav.logout': 'लॉग आउट',
    'nav.studentPortal': 'विद्यार्थी पोर्टल',
    'nav.learningLab': 'न्यूरल मेमरी लॅब',
    'nav.streak': 'सातत्य (Streak)',
    'nav.sparks': 'स्पार्क्स',
    'nav.days': 'दिवस',

// Drawer & Navigation
    'nav.navigation': 'नेव्हिगेशन',
    'nav.programsMasterclasses': 'अभ्यासक्रम आणि मास्टरक्लास',
    'nav.explore': 'ब्रेनसेतु जाणून घ्या',
    'nav.about': 'आमच्याबद्दल',
    'nav.aboutDesc': 'आमचा दृष्टिकोन, तत्वज्ञान आणि ध्येय',
    'nav.approach': 'शिकण्याची पद्धत',
    'nav.approachDesc': '६-टप्प्यांची प्रभुत्व पद्धत',
    'nav.tech': 'तंत्रज्ञान',
    'nav.techDesc': 'डिजिटल सराव आणि इंटेलीया360 साधने',
    'nav.studentDev': 'विद्यार्थी विकास',
    'nav.studentDevDesc': 'संज्ञानात्मक कौशल्ये आणि सर्वांगीण विकास',
    'nav.forParents': 'पालकांसाठी',
    'nav.forParentsDesc': 'पालक मार्गदर्शन आणि शैक्षणिक उणीवांचे निदान',
    'nav.contactAdmissions': 'संपर्क आणि प्रवेश',
    'nav.contactDesc': 'डायग्नोस्टिक सल्लामसलतीची वेळ निश्चित करा',
    'nav.studentPortalDesc': 'न्यूरल मेमरी लॅब (मॉड्यूल ३) वापरण्यासाठी आणि प्रगती सेव्ह करण्यासाठी साइन इन करा.',
    'nav.launchLab': 'न्यूरल मेमरी लॅब उघडा',
    'nav.bookConsultation': 'डायग्नोस्टिक सल्लामसलत बुक करा',
    'nav.academyAddress': 'फेलिज फ्लो स्टुडिओ, हिरानंदानी ट्रस्ट स्कूलजवळ, पनवेल – ४१०२०७',
    'nav.privacyPolicy': 'गोपनीयता धोरण',
    'nav.terms': 'नियम आणि अटी',

    // About Page
    'about.breadcrumb': 'आमच्याबद्दल',
    'about.heroTitle': 'ब्रेनसेतु अकादमीबद्दल',
    'about.heroDesc1': 'ब्रेनसेतु अकादमी हा एक आधुनिक शिक्षण आणि विद्यार्थी-विकास उपक्रम आहे जो घोकंपट्टी आणि परीक्षेची भीती नाहीशी करण्यासाठी तयार केला गेला आहे.',
    'about.heroDesc2': '"सेतु" म्हणजे पूल. ब्रेनसेतु हा बौद्धिक आणि मानसिक पूल आहे जो जोडतो:',
    'about.bridgeKnowledge': 'ज्ञान (Knowledge)',
    'about.bridgeMemory': 'स्मरण (Memory)',
    'about.bridgeConcepts': 'संकल्पना (Concepts)',
    'about.bridgeApplication': 'उपयोजन (Application)',
    'about.bridgePotential': 'सुप्त क्षमता (Potential)',
    'about.philosophyTitle': 'आमचे तत्वज्ञान',
    'about.philosophyDesc': 'आम्ही निर्भय, आत्मविश्वासू आणि आयुष्यभर विचार करणारे विद्यार्थी घडवण्यासाठी गणितीय तर्क, स्मरण पद्धती आणि वैयक्तिक मार्गदर्शन यांचा संगम साधतो.',

    // Learning Approach Page
    'approach.breadcrumb': 'शिकण्याची पद्धत',
    'approach.heroTitle': 'ब्रेनसेतु शिकण्याची पद्धत',
    'approach.heroSubtitle': 'संरचित संज्ञानात्मक प्रगती आणि वैज्ञानिक स्मरण तंत्रांद्वारे केवळ पाठांतराकडून चिरस्थायी समजेकडे वाटचाल.',
    'approach.stepTitle': 'सहा-टप्प्यांची प्रभुत्व प्रगती',
    'approach.stepSubtitle': 'प्रत्येक संकल्पना एका उद्देशपूर्ण क्रमाने शिकवली जाते जी गुंतागुंतीच्या प्रश्नांपूर्वी सहज स्पष्टता निर्माण करते.',

    // Technology Page
    'technology.breadcrumb': 'तंत्रज्ञान आणि एआय',
    'technology.heroTitle': 'मानवी समजेला बळ देणारे तंत्रज्ञान',
    'technology.heroSubtitle': 'आमचा असा विश्वास आहे की तंत्रज्ञान कधीही उत्तम शिक्षकाची जागा घेऊ शकत नाही. त्याऐवजी, ते अमूर्त गणिताला दृश्यमान आणि सहज समजण्यायोग्य बनवण्यास मदत करते.',
    'technology.exploreBtn': 'अभ्यासक्रम पहा',
    'technology.enquireBtn': 'डायग्नोस्टिक चाचणी बुक करा',

    // Student Development Page
    'studentDev.breadcrumb': 'विद्यार्थी विकास',
    'studentDev.heroTitle': 'सर्वांगीण विचारवंताची घडण',
    'studentDev.heroSubtitle': 'संज्ञानात्मक कौशल्ये, भावनिक संतुलन आणि अभ्यासाची शिस्त जी केवळ परीक्षांपुरती मर्यादित न राहता आयुष्यभर साथ देते.',
    'studentDev.outcomesTitle': 'आठ मूलभूत संज्ञानात्मक क्षमता',
    'studentDev.outcomesSubtitle': 'ब्रेनसेतुसोबतच्या प्रवासात प्रत्येक विद्यार्थ्यामध्ये या मूलभूत बौद्धिक क्षमतांचा विकास होतो.',

    // Parents Page
    'parents.breadcrumb': 'पालकांसाठी',
    'parents.heroTitle': 'आपले मूल कसे शिकते हे पालकांना समजून घेणे',
    'parents.heroSubtitle': 'गणिताची भीती म्हणजे बुद्धिमत्तेचा अभाव नव्हे; तर ती पूर्वीच्या संकल्पनेतील त्रुटी किंवा चुकीच्या शिक्षण पद्धतीमुळे असते. आम्ही पालकांना स्पष्टता आणि मार्गदर्शन देतो.',
    'parents.bookBtn': 'सल्लामसलत / मूल्यांकन चौकशी नोंदवा',
    'parents.exploreBtn': 'शिफारस केलेले अभ्यासक्रम पहा',

    // Contact Page
    'contact.breadcrumb': 'संपर्क आणि प्रवेश',
    'contact.heroTitle': 'संपर्क आणि डायग्नोस्टिक प्रवेश',
    'contact.heroSubtitle': 'तुमच्या पाल्यासाठी १-ऑन-१ डायग्नोस्टिक मार्गदर्शनासाठी आमच्या तज्ज्ञ शिक्षकांशी चर्चा करा किंवा पनवेल केंद्रास भेट द्या.',
    'contact.addressTitle': 'पनवेल शिक्षण केंद्र',
    'contact.hoursTitle': 'कामाचे तास',
    'contact.hoursDesc': 'सोमवार - शनिवार: सकाळी १०:०० ते संध्याकाळी ७:३०',
    'contact.phoneTitle': 'फोन आणि व्हॉट्सअॅप',
    'contact.formTitle': 'डायग्नोस्टिक सल्लामसलतीची वेळ निश्चित करा',
    'contact.formSubtitle': 'खालील फॉर्म भरा आणि आमचे शैक्षणिक समुपदेशक २४ तासांच्या आत तुमच्याशी संपर्क साधतील.',

    'about.visionBadge': 'आमचा दृष्टिकोन',
    'about.visionQuote': 'केवळ माहिती पाठांतर न करता, ज्ञान समजून घेणारे, लक्षात ठेवणारे, उपयोजन करणारे आणि आत्मविश्वासाने वापरणारे विद्यार्थी घडवणे.',
    'about.philosophyBadge': 'मार्गदर्शक तत्त्व',
    'about.philosophyHeading': 'आमचे तत्वज्ञान',
    'about.philosophyQuote': '“शिक्षणाने समज निर्माण केली पाहिजे, केवळ पाठांतर नव्हे.”',
    'about.activePartTitle': 'सक्रिय सहभाग',
    'about.activePartDesc': 'विद्यार्थ्यांनी आपल्या शिकण्याच्या प्रवासात सक्रियपणे सहभागी झाले पाहिजे—सूत्रे न रटता प्रश्न विचारणे, प्रयोग करणे, निष्कर्ष काढणे आणि ते सिद्ध करणे.',
    'about.holisticDevTitle': 'सर्वांगीण विकास',
    'about.holisticDevDesc': 'शैक्षणिक कामगिरी आणि बौद्धिक कौशल्ये यांचा विकास एकत्र झाला पाहिजे. परीक्षेत मिळणारे चांगले गुण हे बौद्धिक प्रभुत्वाचे स्वाभाविक फळ आहेत.',
    'about.missionBadge': 'ध्येय आणि कार्य',
    'about.missionTitle': 'आमचे अष्टसूत्री ध्येय (Eight-Fold Mission)',
    'about.missionSubtitle': 'आमचा अभ्यासक्रम, वैयक्तिक मार्गदर्शन आणि तंत्रज्ञान यांना योग्य दिशा देणाऱ्या ठोस व मोजता येणाऱ्या वचनबद्धता.',
    'about.corePillar': 'मुख्य स्तंभ',
    'about.mission1Title': 'स्मरणशक्ती आणि धारणा सुधारणे',
    'about.mission1Desc': 'अल्पकालीन घोकंपट्टीऐवजी दीर्घकाळ टिकणारी अर्थपूर्ण स्मरण तंत्रे रुजवा.',
    'about.mission2Title': 'तार्किक आणि विश्लेषणात्मक विचार विकसित करणे',
    'about.mission2Desc': 'संरचित अनुमानात्मक तर्क आणि टप्प्याटप्प्याने विचार करण्याची स्पष्टता निर्माण करा.',
    'about.mission3Title': 'शैक्षणिक मूलभूत संकल्पना बळकट करणे',
    'about.mission3Desc': 'मागील वर्षांतील संकल्पनात्मक त्रुटी दूर करा जेणेकरून पुढील गणित शिकणे सहज होईल.',
    'about.mission4Title': 'शिक्षण आनंददायी आणि रंजक बनवणे',
    'about.mission4Desc': 'भीतीदायक समीकरणांचे रूपांतर परस्परसंवादी, दृश्य शोध आणि गणिती कोड्यांमध्ये करा.',
    'about.mission5Title': 'पाठांतरावर अवलंबून राहणे कमी करणे',
    'about.mission5Desc': 'मूळ संकल्पना समजून घेण्यास प्रोत्साहन द्या: सूत्रे लक्षात ठेवण्यापूर्वी ती कशी आली ते समजून घ्या.',
    'about.mission6Title': 'शैक्षणिक आत्मविश्वास निर्माण करणे',
    'about.mission6Desc': 'नवीन आणि आव्हानात्मक गणिताच्या समस्या सोडवताना भीती न बाळगता संयम व आत्मविश्वास ठेवा.',
    'about.mission7Title': 'वैयक्तिक शैक्षणिक मार्गदर्शन',
    'about.mission7Desc': 'प्रत्येक विद्यार्थ्याची शिकण्याची पद्धत ओळखून वैयक्तिक मार्गदर्शन प्रदान करणे.',
    'about.mission8Title': 'आधुनिक तंत्रज्ञानाचा सुयोग्य वापर',
    'about.mission8Desc': 'अनुभवी शिक्षकांच्या मार्गदर्शनाला आधुनिक इंटेलीया360 तंत्रज्ञानाची जोड देणे.',
    'whoWeServe.badge': 'विकासाचे टप्पे',
    'whoWeServe.title': 'प्रत्येक टप्प्यासाठी विशेष तयार केलेले शिक्षण',
    'whoWeServe.subtitle': 'खेळावर आधारित प्राथमिक पॅटर्न ओळखीपासून ते ऑलिम्पियाडच्या कठीण गणितांपर्यंत, आमचा अभ्यासक्रम प्रत्येक टप्प्यासाठी सज्ज आहे.',
    'whoWeServe.exploreBtn': 'अभ्यासक्रमाचे टप्पे पहा',
    'whoWeServe.stage1Stage': 'पूर्व-प्राथमिक',
    'whoWeServe.stage1Age': 'वय ४ – ६ वर्षे',
    'whoWeServe.stage1Headline': 'कुतूहल आणि मूलभूत विचारसरणी',
    'whoWeServe.stage1Desc': 'खेळाच्या माध्यमातून संख्यांचे ज्ञान, दिशांचे भान आणि पॅटर्न ओळख विकसित करा.',
    'whoWeServe.stage1Badge': 'आरंभिक अन्वेषक',
    'whoWeServe.stage2Stage': 'प्राथमिक शाळा',
    'whoWeServe.stage2Age': 'इयत्ता १ – ५',
    'whoWeServe.stage2Headline': 'गणिताचा मजबूत पाया',
    'whoWeServe.stage2Desc': 'साध्या गणिताचे रूपांतर मजबूत वैचारिक पायामध्ये करा, गणिताची भीती मुळापासून नष्ट करा.',
    'whoWeServe.stage2Badge': 'मूलभूत पाया',
    'whoWeServe.stage3Stage': 'माध्यमिक शाळा',
    'whoWeServe.stage3Age': 'इयत्ता ६ – ८',
    'whoWeServe.stage3Headline': 'संकल्पनात्मक समज आणि तर्कशुद्ध विचार',
    'whoWeServe.stage3Desc': 'संख्यांचे रूपांतर बीजगणित, भूमिती आणि स्मरण तंत्रांशी जोडून विचारक्षमता वाढवा.',
    'whoWeServe.stage3Badge': 'संकल्पना निर्माते',
    'whoWeServe.stage4Stage': 'हायस्कूल',
    'whoWeServe.stage4Age': 'इयत्ता ९ – १०',
    'whoWeServe.stage4Headline': 'शैक्षणिक प्राविण्य आणि समस्या निवारण',
    'whoWeServe.stage4Desc': 'बोर्ड परीक्षांचा अभ्यासक्रम, टप्प्याटप्प्याने प्रश्न सोडवणे आणि उच्च विचारसरणी आत्मसात करा.',
    'whoWeServe.stage4Badge': 'बोर्ड प्राविण्य',
    'whoWeServe.stage5Stage': 'उच्च माध्यमिक',
    'whoWeServe.stage5Age': 'इयत्ता ११ – १२',
    'whoWeServe.stage5Headline': 'प्रगत गणित आणि स्पर्धा परीक्षांचा पाया',
    'whoWeServe.stage5Desc': 'ऑलिम्पियाड पद्धती, प्रगत कॅल्क्युलस आणि सखोल विश्लेषणात्मक गणित सोडवण्याची तयारी करा.',
    'whoWeServe.stage5Badge': 'स्पर्धात्मक आघाडी',
    'parents.pillarsBadge': 'पालक सक्षमीकरण',
    'parents.pillarsTitle': 'आमच्या पालक मार्गदर्शनाचे ५ मुख्य स्तंभ',
    'parents.pillarsSubtitle': 'पालकांना माहितीपूर्ण, आधार देणारे आणि विद्यार्थ्याच्या प्रगतीबद्दल आश्वस्त ठेवणारे आमचे ठोस मार्ग.',
    'parents.pillar1Title': 'शिकण्याची शैली समजून घ्या',
    'parents.pillar1Desc': 'आपले मूल दृश्य, मौखिक किंवा संख्यात्मक संकल्पना कशा समजते हे जाणून घ्या जेणेकरून चिडचिड न होता मदत करता येईल.',
    'parents.pillar2Title': 'अज्ञातातील शैक्षणिक उणीवा ओळखा',
    'parents.pillar2Desc': 'मागील वर्षांतील अशा त्रुटी ओळखा ज्या आज गणिताच्या भीतीचे कारण बनत आहेत.',
    'parents.pillar3Title': 'सर्वांगीण बौद्धिक विकासावर लक्ष ठेवा',
    'parents.pillar3Desc': 'एकाग्रतेचा कालावधी, स्मरणशक्ती आणि स्वतंत्रपणे अभ्यास करण्याच्या सवयींची नोंद ठेवा.',
    'parents.pillar4Title': 'मार्गदर्शन आणि प्रगती अहवाल',
    'parents.pillar4Desc': 'पारदर्शक, उपयुक्त अभिप्राय आणि तज्ज्ञ शिक्षकांशी थेट चर्चा करण्याची सुविधा.',
    'parents.pillar5Title': 'घरी अभ्यासाचे उत्तम वातावरण निर्माण करा',
    'parents.pillar5Desc': 'गृहपाठाची वेळ तणावमुक्त आणि आनंददायी करण्यासाठी उपयुक्त पालकत्व पद्धती.',
    'parents.journeyBadge': 'पालक प्रवास',
    'parents.journeyTitle': '७-टप्प्यांचा पालक भागीदारी प्रवास',
    'parents.journeySubtitle': 'सुरुवातीच्या माहिती चौकशीपासून ते दीर्घकालीन बौद्धिक विकासापर्यंत कुटुंबांना योग्य दिशा.',
    'approach.methodBadge': 'प्रगती आराखडा',
    'approach.methodTitle': 'सहा-टप्प्यांची प्रभुत्व प्रगती',
    'approach.methodSubtitle': 'प्रत्येक संकल्पना एका उद्देशपूर्ण क्रमाने शिकवली जाते जी कठीण प्रश्नांपूर्वी अंतर्ज्ञानाची स्पष्टता देते.',
    'approach.stepFocus': 'मुख्य भर:',
    'approach.stepBridge': 'सेतू:',
    'approach.techBadge': 'प्रत्यक्ष संज्ञानात्मक विज्ञान',
    'approach.techTitle': 'सहा संज्ञानात्मक स्मरण तंत्रे',
    'approach.techSubtitle': 'परीक्षेच्या दबावाखालीही स्मरणशक्ती अचूक आणि विश्वासार्ह ठेवणारी वैज्ञानिक साधने.',
    'approach.techHow': 'हे कसे कार्य करते:',
    'approach.techExample': 'वर्गातील उदाहरण:',
    'approach.tech1Name': 'संकल्पना चंकिंग (Concept Chunking)',
    'approach.tech1Desc': 'मोठी सूत्रे आणि संकल्पनांचे छोट्या, सुटसुटीत भागांमध्ये विभाजन करणे.',
    'approach.tech1How': 'आपली स्मरणशक्ती एका वेळी ४-७ गोष्टी सहज लक्षात ठेवू शकते. लांबलचक पायऱ्या ३ मुख्य भागात मांडल्याने गणित सोपे वाटते.',
    'approach.tech1Example': 'बहुपदी अवयव पद्धती: सामाईक पद -> सूत्र जुळणी -> मधल्या पदाची फोड.',
    'approach.tech2Name': 'तार्किक संबंध (Logical Connections)',
    'approach.tech2Desc': 'नवीन विषयांना आधीच शिकलेल्या संकल्पनांशी जोडणे.',
    'approach.tech2How': 'मेंदू संबंधांद्वारे लक्षात ठेवतो. जेव्हा विद्यार्थी पाहतात की निर्देशक भूमिती म्हणजे बीजगणित आणि भूमितीचा संगम आहे, तेव्हा ते सहज समजते.',
    'approach.tech2Example': 'पायथागोरस सिद्धांताचा थेट अंतर सूत्र आणि वर्तुळाच्या समीकरणाशी संबंध जोडणे.',
    'approach.tech3Name': 'सक्रिय आठवण सराव (Active Retrieval)',
    'approach.tech3Desc': 'वारंवार आठवून पाहण्याच्या सरावातून स्मृती कायमस्वरूपी दृढ करणे.',
    'approach.tech3How': 'केवळ पुस्तक वाचल्याने समजल्याचा भास होतो. पुस्तक मिटवून स्वतःहून सूत्र सिद्ध करण्याचा प्रयत्न केल्यास स्मृती पक्की होते.',
    'approach.tech3Example': '५ मिनिटांचे छोटे आव्हान ज्यामध्ये विद्यार्थी सूत्राची सिद्धता स्वतः लिहून पाहतात.',
    'approach.tech4Name': 'दृश्य जोडणी (Visual Associations)',
    'approach.tech4Desc': 'अमूर्त चिन्हांना चित्रांच्या आणि आकृत्यांच्या रूपात पाहणे.',
    'approach.tech4How': 'दृश्य स्मृती अत्यंत वेगाने आणि दीर्घकाळ काम करते. आम्ही विद्यार्थ्यांना समीकरणे तराजूच्या स्वरूपात पाहायला शिकवतो.',
    'approach.tech4Example': 'समीकरणांना संतुलित तराजूच्या रूपात पाहणे जिथे दोन्ही बाजूंना समान बदल करावे लागतात.',
    'approach.tech5Name': 'पॅटर्न ओळख (Pattern Recognition)',
    'approach.tech5Desc': 'वेगवेगळ्या प्रश्नांमधील सामाईक गणितीय रचना ओळखणे.',
    'approach.tech5How': 'गणितज्ञ हजारो वेगवेगळे प्रश्न सोडवत नाहीत; ते त्यामागील मूळ रचना ओळखतात.',
    'approach.tech5Example': 'संख्यांच्या मालिकांमध्ये आणि समीकरणांमध्ये सममिती शोधणे.',
    'approach.tech6Name': 'योग्य अंतराने पुनरावृत्ती (Spaced Revision)',
    'approach.tech6Desc': 'वैज्ञानिकदृष्ट्या ठरवलेल्या कालावधीनंतर संकल्पनांची उजळणी करणे.',
    'approach.tech6How': 'विसरण्याच्या नैसर्गिक प्रवृत्तीवर मात करणे. दिवस १, ३, ७ आणि २१ ला उजळणी केल्याने ज्ञान कायमचे लक्षात राहते.',
    'approach.tech6Example': 'स्मृती कमी होण्याच्या वेळी ठरवलेली १० मिनिटांची अचूक उजळणी.',
    'technology.pillarsBadge': 'एकात्मिक शिक्षण पद्धती',
    'technology.pillarsTitle': 'ब्रेनसेतु अनुभवाचे तीन मुख्य स्तंभ',
    'technology.pillarsSubtitle': 'प्रत्येक पद्धत विद्यार्थ्याच्या बौद्धिक विकासात मोलाची भर घालते.',
    'technology.pillar1Title': 'प्रत्यक्ष शिक्षण (Physical Learning)',
    'technology.pillar1Tag': 'शिक्षकांचे प्रत्यक्ष मार्गदर्शन',
    'technology.pillar1Desc': 'आत्मविश्वास वाढवण्यासाठी अनुभवी शिक्षकांचे वैयक्तिक लक्ष, चर्चा आणि सुलभ मार्गदर्शन.',
    'technology.pillar2Title': 'डिजिटल शिक्षण (Digital Learning)',
    'technology.pillar2Tag': 'परस्परसंवादी सॉफ्टवेअर आणि व्हिज्युअल्स',
    'technology.pillar2Desc': 'गतिमान गणितीय व्हिज्युअलायझेशन, परस्परसंवादी भूमिती साधने आणि खेळाच्या स्वरूपातील सराव.',
    'technology.pillar3Title': 'एआय-आधारित मूल्यमापन',
    'technology.pillar3Tag': 'इंटेलीया360 लर्निंग इंजिन',
    'technology.pillar3Desc': 'बुद्धिमान डायग्नोस्टिक मूल्यमापन, वैयक्तिक उजळणी सूचना आणि तपशीलवार प्रगती ट्रॅकिंग.',
    'technology.featuresBadge': 'डिजिटल तंत्रज्ञान',
    'technology.featuresTitle': 'भविष्यासाठी सज्ज इंटेलीया360 इकोसिस्टम',
    'technology.featuresSubtitle': 'विद्यार्थ्यांचा सराव, डायग्नोस्टिक चाचण्या आणि विश्लेषण एकत्र आणणारे प्रगत सॉफ्टवेअर इंजिन.',
    'studentDev.pillarsBadge': 'संज्ञानात्मक क्षमतांची मांडणी',
    'studentDev.pillarsTitle': 'विद्यार्थी विकासाचे नऊ मुख्य स्तंभ',
    'studentDev.pillarsSubtitle': 'ब्रेनसेतु अकादमीमधील पद्धती आणि शैक्षणिक व्यायाम समजून घेण्यासाठी प्रत्येक कौशल्यावर क्लिक करा.',
    'studentDev.mechanismLabel': 'संज्ञानात्मक पद्धत:',
    'studentDev.drillLabel': 'ब्रेनसेतु शैक्षणिक सराव:',
    'studentDev.outcomeLabel': 'मोजता येणारा परिणाम:',
    'studentDev.trackingTitle': 'डायग्नोस्टिक विश्लेषण डॅशबोर्ड पूर्वावलोकन',
    'studentDev.trackingSubtitle': 'सरावादरम्यान विद्यार्थ्यांची मानसिक क्षमता आणि गणितीय स्मरणशक्तीची थेट नोंद.',
    'contact.formHeading': 'सल्लामसलतीची वेळ निश्चित करा',
    'contact.formSub': 'खालील फॉर्म भरा आणि आमची शैक्षणिक समुपदेशक टीम २४ तासांत आपल्याशी संपर्क साधेल.',
    'contact.nameLabel': 'पालक / विद्यार्थ्याचे पूर्ण नाव',
    'contact.namePlaceholder': 'उदा. रमेश शर्मा',
    'contact.gradeLabel': 'विद्यार्थ्याची इयत्ता / वर्ग',
    'contact.gradePlaceholder': 'उदा. इयत्ता ७ वी, CBSE / State Board',
    'contact.phoneLabel': 'मोबाईल नंबर / व्हॉट्सअॅप',
    'contact.phonePlaceholder': '+91 98765 43210',
    'contact.emailLabel': 'ईमेल पत्ता',
    'contact.emailPlaceholder': 'parent@example.com',
    'contact.programLabel': 'इच्छुक अभ्यासक्रम',
    'contact.methodLabel': 'संपर्काचे पसंतीचे माध्यम',
    'contact.messageLabel': 'संदेश / अभ्यासातील अडचणी (पर्यायी)',
    'contact.messagePlaceholder': 'आपल्या पाल्याला कोणत्या संकल्पनांमध्ये अडचण येते ते सांगा...',
    'contact.submitBtn': 'डायग्नोस्टिक चौकशी पाठवा',
    'contact.submittingBtn': 'पाठवत आहे...',
    'contact.privacyNotice': 'आम्ही आपल्या गोपनीयतेचा आदर करतो. आपली संपर्क माहिती पूर्णपणे सुरक्षित राहील.',

    // Hero
    'hero.badge': 'अग्रगण्य कॉग्निटिव्ह आणि गणित अकादमी',
    'hero.titleLine1': 'हुशार मनांची घडण.',
    'hero.titleLine2': 'आत्मविश्वासू विद्यार्थ्यांची निर्मिती.',
    'hero.subtitle': 'वेगाने शिका, अधिक चांगले लक्षात ठेवा, हुशारीने विचार करा आणि आत्मविश्वासाने कामगिरी करा. ब्रेनसेतु हे ज्ञान → समज → उपयोजन → आत्मविश्वास यामधील सेतू आहे.',
    'hero.exploreBtn': 'अभ्यासक्रम पहा',
    'hero.enquireBtn': 'चौकशी करा',
    'hero.statStudents': '१०,०००+ विद्यार्थ्यांना मार्गदर्शन',
    'hero.statRetention': '१० पट स्मरणशक्ती',
    'hero.statConfidence': '९८% गणितातील आत्मविश्वास',

    // Impact Section
    'impact.badge': 'आमचा प्रभाव',
    'impact.title': 'उत्कृष्टतेचा सिद्ध ट्रॅक रेकॉर्ड',
    'impact.subtitle': 'संशोधनावर आधारित संज्ञानात्मक आणि संकल्पनात्मक शिक्षण पद्धतींद्वारे देशभरातील विद्यार्थी, शिक्षक आणि शाळांना सक्षम करणे.',
    'impact.stat1Label': 'यशस्वी नोंदणी',
    'impact.stat2Label': 'सक्रिय सदस्य',
    'impact.stat3Label': 'वर्षांचा अनुभव',
    'impact.stat4Label': 'थेट वेबिनार',
    'impact.stat5Label': 'चर्चासत्रे आणि कार्यशाळा',
    'impact.stat6Label': 'सहभागी शाळा',

    // Why BrainSetu Section
    'why.title': 'केवळ शिक्षणापेक्षा बरेच काही',
    'why.subtitle': 'ब्रेनसेतु गणित, संज्ञानात्मक विकास, स्मरण तंत्रे, वैयक्तिक मार्गदर्शन आणि तंत्रज्ञान एकत्र आणून अधिक अर्थपूर्ण शिकण्याचा अनुभव निर्माण करते.',
    'why.benefit1Title': 'संकल्पनात्मक शिक्षण',
    'why.benefit1Desc': 'नियम केवळ पाठांतर करण्याऐवजी गणितीय संबंधांमागील "का" हे समजून घ्या.',
    'why.benefit2Title': 'तार्किक विचारसरणी',
    'why.benefit2Desc': 'संरचित निष्कर्ष, पॅटर्न ओळख आणि विश्लेषणात्मक स्पष्टता विकसित करा जी सर्व क्षेत्रांत उपयोगी ठरते.',
    'why.benefit3Title': 'स्मरणशक्ती तंत्रे',
    'why.benefit3Desc': 'वैज्ञानिक संकल्पना चंकिंग आणि सक्रिय आठवण पद्धती ज्या दीर्घकाळ लक्षात ठेवणे सोपे आणि तणावमुक्त करतात.',
    'why.benefit4Title': 'समस्या निवारण आणि तंत्रज्ञान',
    'why.benefit4Desc': 'आधुनिक डिजिटल गणित साधनांद्वारे समर्थित स्वतंत्र समस्या निवारण कौशल्ये.',

    // Video Showcase Section
    'video.badge': 'अधिकृत व्हिडिओ सादरीकरण',
    'video.title': 'ब्रेनसेतुचे प्रत्यक्ष कार्य पहा',
    'video.subtitle': 'आमची संज्ञानात्मक शिक्षण पद्धती आणि इंटेलीया ३६० मॅथेमॅटिक्स प्रोग्राम विद्यार्थ्यांमध्ये संकल्पनात्मक स्पष्टता, तार्किक विचार आणि आत्मविश्वास कसा घडवतात ते पहा.',
    'video.feat1Title': 'संकल्पनात्मक स्पष्टता',
    'video.feat1Desc': 'पाठांतर न करता मूळ सिद्धांतांवर आधारित गणितीय विचार.',
    'video.feat2Title': '१० पट स्मरणशक्ती',
    'video.feat2Desc': 'वैज्ञानिक संकल्पना चंकिंग आणि न्यूरल स्मरण तंत्रे.',
    'video.feat3Title': 'तज्ज्ञ मार्गदर्शन',
    'video.feat3Desc': 'आधुनिक डिजिटल सराव साधनांसह अनुभवी शिक्षकांचे वैयक्तिक लक्ष.',
    'video.watchYoutube': 'थेट यूट्यूबवर पहा',

    // Learning Journey Section
    'journey.title': 'शिकण्याचा प्रवास',
    'journey.subtitle': 'एक स्पष्ट सहा-टप्प्यांची संज्ञानात्मक प्रगती जी नवीन संकल्पनांना कायमस्वरूपी समज आणि प्रभुत्वात रूपांतरित करते.',
    'journey.stage': 'टप्पा',
    'journey.step1Title': 'शिका (Learn)',
    'journey.step1Desc': 'सहज ज्ञान आणि वास्तविक जगातील कुतूहलासह संकल्पनेची ओळख करून द्या.',
    'journey.step2Title': 'समजून घ्या (Understand)',
    'journey.step2Desc': 'मूळ सिद्धांतांपासून संकल्पनात्मक स्पष्टता निर्माण करा.',
    'journey.step3Title': 'लक्षात ठेवा (Remember)',
    'journey.step3Desc': 'स्मरण तंत्रे आणि न्यूरल कनेक्शनचा वापर करून स्मृती दृढ करा.',
    'journey.step4Title': 'सराव करा (Practice)',
    'journey.step4Desc': 'काळजीपूर्वक तयार केलेल्या सराव संचांद्वारे सराव मजबूत करा.',
    'journey.step5Title': 'उपयोजन करा (Apply)',
    'journey.step5Desc': 'कठीण समस्या आणि वास्तविक जीवनातील प्रसंगांमध्ये ज्ञानाचा वापर करा.',
    'journey.step6Title': 'प्रभुत्व मिळवा (Master)',
    'journey.step6Desc': 'प्रगती ट्रॅक करा, त्रुटी दूर करा आणि चिरस्थायी प्राविण्य मिळवा.',

    // Programs Section
    'programs.sectionBadge': 'संज्ञानात्मक आणि गणित मार्ग',
    'programs.sectionTitle': 'प्रभावी शिक्षणासाठी डिझाइन केलेले अभ्यासक्रम',
    'programs.sectionSubtitle': 'आमचा विशेष स्मरणशक्ती मास्टरक्लास आणि संकल्पनात्मक गणित अभ्यासक्रमातून निवडा.',
    'programs.enquireBtn': 'चौकशी करा आणि डायग्नोस्टिक बुक करा',
    'programs.original': 'मूळ किंमत:',
    'programs.webinarTitle': '10X मेमरी पॉवर वेबिनार',
    'programs.webinarShortDesc': 'तुमची स्मरणशक्ती १० पटीने वाढवण्यासाठी टप्प्याटप्प्याने मार्गदर्शन करणारा कोर्स. जागतिक मेमरी चॅम्पियन्स वापरत असलेल्या तंत्रांचा अभ्यास करा.',
    'programs.webinarBadge': 'खास ऑफर',
    'programs.webinarPerPass': '/ प्रवेश',
    'programs.webinarLink': 'वेबिनार अभ्यासक्रम व तपशील पहा',
    'programs.mathTitle': 'इंटेलेलिया 360° गणित अभ्यासक्रम',
    'programs.mathBadge': 'फ्लॅगशिप',
    'programs.mathShortDesc': 'मूळ संकल्पनांची स्पष्टता, तार्किक विचार आणि बौद्धिक क्षमतेचा विकास यावर लक्ष केंद्रित करणारा सर्वसमावेशक गणित अभ्यासक्रम.',
    'programs.mathPerTerm': '/ सत्र',
    'programs.mathLink': 'संपूर्ण गणित अभ्यासक्रम पहा',
    'programs.flagshipTag': 'प्रमुख शैक्षणिक अभ्यासक्रम',

    // Technology Section
    'tech.title': 'शिक्षणाला पूरक तंत्रज्ञान — पर्याय नाही',
    'tech.subtitle': 'ब्रेनसेतु समज दृढ करण्यासाठी आणि सरावात सातत्य ठेवण्यासाठी प्रत्यक्ष मार्गदर्शनाला डिजिटल साधनांशी जोडते.',
    'tech.pillar1Title': 'प्रत्यक्ष शिक्षण (Physical Learning)',
    'tech.pillar1Desc': 'आत्मविश्वास वाढवण्यासाठी तज्ज्ञ शिक्षकांचे मार्गदर्शन, संवादात्मक चर्चा आणि वैयक्तिक लक्ष.',
    'tech.pillar2Title': 'डिजिटल शिक्षण (Digital Learning)',
    'tech.pillar2Desc': 'संकल्पना सहज समजण्यासाठी गतिमान गणितीय व्हिज्युअलायझेशन आणि खेळाच्या स्वरूपातील सराव.',
    'tech.pillar3Title': 'एआय साहाय्य (AI Support)',
    'tech.pillar3Desc': 'बुद्धिमान डायग्नोस्टिक मूल्यांकन, वैयक्तिक सराव शिफारसी आणि प्रगती ट्रॅकिंग.',
    'tech.keyCapabilities': 'महत्त्वाची शिक्षण वैशिष्ट्ये:',
    'tech.feat1': 'संवादात्मक शिक्षण',
    'tech.feat2': 'डिजिटल सराव',
    'tech.feat3': 'गेमिफिकेशन',
    'tech.feat4': 'मूल्यांकन',
    'tech.feat5': 'प्रगती ट्रॅकिंग',
    'tech.feat6': 'वैयक्तिकृत सराव',

    // Student Development Section
    'dev.title': 'गुणांच्या पलीकडचे सर्वांगीण शिक्षण',
    'dev.subtitle': 'आम्ही आठ मूलभूत संज्ञानात्मक आणि शैक्षणिक क्षमता विकसित करतो ज्या विद्यार्थ्यांना आयुष्यभराच्या बौद्धिक विकासासाठी सज्ज करतात.',
    'dev.outcome1Title': 'स्मरणशक्ती (Memory)',
    'dev.outcome1Desc': 'संकल्पना चंकिंग आणि संरचित स्मरण तंत्रे.',
    'dev.outcome2Title': 'एकाग्रता (Concentration)',
    'dev.outcome2Desc': 'दीर्घकाळ लक्ष केंद्रित ठेवण्याची आणि एकाग्रतेची क्षमता.',
    'dev.outcome3Title': 'तर्कक्षमता (Reasoning)',
    'dev.outcome3Desc': 'तार्किक विचार आणि पायऱ्यांची योग्य पडताळणी.',
    'dev.outcome4Title': 'सर्जनशीलता (Creativity)',
    'dev.outcome4Desc': 'जटिल समस्या सोडवण्यासाठी विविध पर्यायांचा शोध घेणे.',
    'dev.outcome5Title': 'समस्या निवारण (Problem-Solving)',
    'dev.outcome5Desc': 'अपरिचित आव्हानांना सामोरे जाण्यासाठी उपयुक्त टूलकिट्स.',
    'dev.outcome6Title': 'तार्किक विचार (Logical Thinking)',
    'dev.outcome6Desc': 'क्रमबद्ध आणि अल्गोरिदमिक विचारांची स्पष्टता.',
    'dev.outcome7Title': 'शैक्षणिक आत्मविश्वास (Academic Confidence)',
    'dev.outcome7Desc': 'कठीण परीक्षांच्या वेळी संयम, संतुलन आणि आत्मविश्वास.',
    'dev.outcome8Title': 'स्वतंत्र शिक्षण (Independent Learning)',
    'dev.outcome8Desc': 'स्वावलंबी अभ्यासाच्या सवयी आणि आत्म-चिंतन.',

    // CTA Section
    'cta.title': 'एक उज्ज्वल शिक्षण प्रवास येथून सुरू होतो',
    'cta.subtitle': 'तुमचे मूल कसे शिकते ते जाणून घ्या आणि आमच्या मोफत डायग्नोस्टिक सल्लामसलतीद्वारे मूलभूत उणीवा ओळखा.',
    'cta.btn': 'चौकशी करा',
    'cta.orCall': 'किंवा थेट फोन करा:',
    'cta.address': '📍 पनवेल केंद्र: फेलिज फ्लो स्टुडिओ, हिरानंदानी ट्रस्ट स्कूलजवळ',
    'common.compareBtn': 'दोन्ही अभ्यासक्रमांची तुलना करा',

    // Modal / Welcome
    'welcome.newTitle': 'ब्रेनसेतु अकादमीमध्ये आपले स्वागत आहे, {name}! 🎉',
    'welcome.newSubtitle': 'तुमचा संज्ञानात्मक शिक्षणाचा प्रवास आजपासून सुरू होत आहे. १० पट स्मरणशक्ती अनलॉक करा आणि संकल्पनात्मक गणितात प्राविण्य मिळवा.',
    'welcome.returningTitle': 'पुन्हा स्वागत आहे, {name}! 👋',
    'welcome.returningSubtitle': 'तुमचा न्यूरल लर्निंग ब्रिज सक्रिय आहे. आजचे मिशन पूर्ण करण्यासाठी आणि शिकण्याचे सातत्य राखण्यासाठी सज्ज आहात का?',
    'welcome.newBadge': 'नवीन विद्यार्थी',
    'welcome.returningBadge': 'सक्रिय न्यूरल विद्यार्थी',
    'welcome.startBtn': 'मिशन सुरू करा 🚀',
    'welcome.resumeBtn': 'शिकणे सुरू ठेवा 🚀',
    'welcome.tip1': 'संवाद साधणारे सिम्युलेटर: अवकाश यांत्रिकी, अपूर्णांक आणि ग्रिड अभ्यासा.',
    'welcome.tip2': 'संज्ञानात्मक सराव: स्मृती दृढ करा.',
    'welcome.streakLabel': 'दैनंदिन सातत्य सक्रिय',
    'welcome.xpLabel': 'मिळालेले स्पार्क्स (XP)',

    // Footer
    'footer.tagline': 'ज्ञान, समज, उपयोजन आणि आत्मविश्वास यामधील शिकण्याचा मजबूत सेतू.',
    'footer.quickLinks': 'जलद नेव्हिगेशन',
    'footer.programs': 'आमचे अभ्यासक्रम',
    'footer.contact': 'संपर्क आणि मदत',
    'footer.forParents': 'पालकांसाठी',
    'footer.studentDev': 'विद्यार्थी विकास',
    'footer.contactEnquire': 'संपर्क / चौकशी',
    'footer.portal': 'विद्यार्थी व पालक पोर्टल',
    'footer.privacy': 'गोपनीयता धोरण',
    'footer.terms': 'नियम आणि अटी',
    'footer.rights': 'सर्व हक्क राखीव. ब्रेनसेतु अकादमी.'
  }
};

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: (key: string, fallback?: string) => fallback || key,
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('brainsetu_language') as Language;
    return saved === 'en' || saved === 'hi' || saved === 'mr' ? saved : 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('brainsetu_language', lang);
    document.documentElement.lang = lang;
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string, fallback?: string): string => {
    const langDict = translations[language] || translations.en;
    if (langDict[key]) {
      return langDict[key];
    }
    if (translations.en[key]) {
      return translations.en[key];
    }
    return fallback || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
